pingcap/docs-tidb-operator

.github/ISSUE_TEMPLATE/change-request.md, .github/ISSUE_TEMPLATE/error-report.md, .github/ISSUE_TEMPLATE/question.md, .github/pull_request_template.md
Add a PR template and three issue templates.
=> .github: add pr and issue templates

zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-from-kubernetes-kind.md, zh/deploy-tidb-from-kubernetes-minikube.md
Update procedures to deploy with kind/minikube/GKE
=> zh: update docs for get-started deployments

zh/upgrade-tidb-operator.md
Update the procedure for tidb-operator upgrade
=> zh: update for tidb-operator upgrade

zh/configure-cluster-using-tidbcluster.md
Fix a few typos in the tidbcluster config doc
- Other reference link(s):  https://github.com/pingcap/docs-tidb-operator/pull/12
=> zh: fix typo in tidbcluster config

zh/deploy-on-general-kubernetes.md, zh/upgrade-a-tidb-cluster.md
=> zh: update docs for tidb cluster upgrade with CR

zh/deploy-on-aws-eks.md
Deploy tidb cluster with cr on aws.
=> zh: update doc for deploy tidb cluster on aws eks

zh/TOC.md, zh/enable-tls-for-mysql-client.md
=> zh: TLS for MySQL Client

zh/TOC.md, zh/access-tidb.md, zh/backup-and-restore-using-helm-charts.md, zh/configure-a-tidb-cluster.md, zh/configure-backup.md, zh/deploy-tidb-operator.md, zh/destroy-a-tidb-cluster.md, zh/monitor-a-tidb-cluster.md, zh/notes-tidb-operator-v1.1.md, zh/prerequisites.md, zh/tidb-cluster-chart-config.md
=> overall update for v1.1

zh/monitor-a-tidb-cluster.md
Update doc for alert and monitoring
=> zh: update for alert and monitoring

zh/deploy-tidb-binlog.md
Update doc to enable tls for binlog
=> zh: update doc to enable tls for binlog

zh/restore-data-using-tidb-lightning.md
update doc for importer deploy
=> zh: update doc for importer deploy

zh/notes-tidb-operator-v1.1.md, zh/troubleshoot.md
=> update notes for v1.1

zh/restore-from-s3.md
add supplementary notes in restore
=> zh: add supplementary notes in restore

zh/deploy-on-alibaba-cloud.md, zh/deploy-on-aws-eks.md, zh/deploy-on-gcp-gke.md, zh/deploy-tidb-from-kubernetes-kind.md, zh/deploy-tidb-operator.md, zh/tidb-toolkit.md
Latest helm version 2.16.4 cannot work, please refer to https://github.com/pingcap/tidb-operator/issues/2033 for more detail.
=> zh: lock helm version

zh/notes-tidb-operator-v1.1.md
=> zh: update v1.1 notes for monitor

en/restore-data-using-tidb-lightning.md
Update doc for importer deploy.
- This PR is translated from:  https://github.com/pingcap/docs-tidb-operator/pull/46
=> en: update doc for importer deploy

.editorconfig, .github/workflows/media.yml
When you upload files In the `media/` folder, this change can help you sync them to Qiniu bucket and AWS s3 bucket automatically.
=> ci: sync media on push

en/use-auto-failover.md, zh/use-auto-failover.md
Update auto-failover default setting.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/2382
=> zh, en: update auto-failover default setting

en/_index.md, en/tidb-operator-overview.md, zh/_index.md, zh/tidb-operator-overview.md
Add the corresponding relationship between TiDB Operator and TiDB
=> en, zh: add tidb-operator relation with tidb

en/TOC.md, en/enable-tidb-cluster-auto-scaling.md
Add TidbCluster Autoscaling document
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/32
=> en: enable TidbCluster Auto-scaling

en/restart-a-tidb-cluster.md
update restart tidbcluster document
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/43
=> en: update restart tidbcluster document

zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-from-kubernetes-kind.md, zh/deploy-tidb-from-kubernetes-minikube.md
Update get-started docs to remove some references.
=> zh: update get-started docs

zh/backup-to-aws-s3-using-br.md, zh/enable-tls-between-components.md, zh/restore-from-aws-s3-using-br.md
=> update docs for br tls

en/TOC.md, en/enable-admission-webhook.md, en/enable-tidb-cluster-auto-scaling.md, en/restart-a-tidb-cluster.md, zh/enable-admission-webhook.md
Add admission webhook document
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/50
=> en: add admission webhook document

en/scale-a-tidb-cluster.md
Update doc for tidb cluster scaling.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/33
=> en: update doc for tidb cluster scaling

zh/enable-tidb-cluster-auto-scaling.md
=> zh: revise auto-scaling document

scripts/generate_pdf.sh
=> update PDF title

en/enable-tidb-cluster-auto-scaling.md
Revise the auto-scaling document.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/131
=> en: revise auto-scaling doc

README.md
- Remove the old description of documentation versions
- Update description on dev and v1.1 branches
=> README: update doc version and branch info

zh/enable-tls-between-components.md, zh/enable-tls-for-mysql-client.md
For every `TidbCluster`, we should use `Issuer` instead of `ClusterIssuer`.
=> zh: use issuer instead of clusterissuer

en/enable-tls-between-components.md
add `cert-allowed-cn` option
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/115
=> en: add `cert-allowed-cn` option

en/enable-tls-for-mysql-client.md, zh/enable-tls-for-mysql-client.md
=> zh, en: fix TLS for client typo

zh/configure-a-tidb-cluster.md
Update local labels description for pd.
=> update local labels description for pd

zh/deploy-on-alibaba-cloud.md, zh/deploy-on-aws-eks.md, zh/deploy-on-gcp-gke.md
Add notes for tidb-operator version.
=> Add notes for tidb-operator version

en/TOC.md, en/api-references.md, zh/TOC.md, zh/api-references.md
=> Add api references

en/enable-admission-webhook.md, zh/enable-admission-webhook.md
=> docs: change failurePolicy from Failure to Fail

en/deploy-on-alibaba-cloud.md, en/deploy-on-aws-eks.md, en/deploy-on-gcp-gke.md
Add notes for tidb-operator version.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/164
=> en: add notes for tidb-operator version

en/deploy-on-alibaba-cloud.md, en/deploy-on-aws-eks.md, en/deploy-on-gcp-gke.md, en/deploy-on-general-kubernetes.md, en/initialize-a-cluster.md, en/monitor-using-tidbmonitor.md, en/notes-tidb-operator-v1.1.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-on-aws-eks.md, zh/deploy-on-gcp-gke.md, zh/deploy-on-general-kubernetes.md, zh/initialize-a-cluster.md, zh/monitor-using-tidbmonitor.md, zh/notes-tidb-operator-v1.1.md
=> en, zh: update link for api reference

en/api-references.md, zh/api-references.md
Remove `tab` in api-referecens that results in branch failure.
=> zh, en: remove tab

zh/enable-tls-between-components.md
=> zh: the certificate commonName should be the same

en/deploy-on-aws-eks.md, zh/deploy-on-aws-eks.md
Update doc for destroy failure on aws.
=> en, zh: update doc for destroy failure on aws

en/configure-a-tidb-cluster.md
Update location labels description for pd.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/161
=> en: update location label description for pd

.circleci/config.yml, .markdownlint.yaml, en/deploy-on-aws-eks.md, en/deploy-on-gcp-gke.md, en/deploy-tidb-binlog.md, en/enable-tls-between-components.md, zh/enable-tls-between-components.md, zh/restart-a-tidb-cluster.md, zh/restore-data-using-tidb-lightning.md, zh/restore-from-aws-s3-using-br.md, zh/scale-a-tidb-cluster.md
Signed-off-by: Aylei <rayingecho@gmail.com>
Add markdownlint in CI
close #11
=> Add markdownlint in CI

.circleci/config.yml, .markdownlint.yaml
Add markdownlint in CI for release-1.0 branch
- Other reference link(s): https://github.com/pingcap/docs-tidb-operator/pull/188
=> *: add markdownlint in CI-v1.0

en/deploy-on-alibaba-cloud.md, en/deploy-on-aws-eks.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-on-aws-eks.md
Fix the second comment in https://internal.pingcap.net/jira/projects/USDOC/issues/USDOC-5.
=> zh, en: improve aws and ack docs

en/tidb-scheduler.md
Remove a wrong line in the table.
=> en: remove extra line in the table

en/enable-tls-for-mysql-client.md, zh/enable-tls-for-mysql-client.md
=> zh,en: remove shell-regular for tls document

en/enable-admission-webhook.md
Update Webhook TLS configuration document.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/171
=> en: update TLS certificate for the admission controller

.github/workflows/ci.yaml, en/backup-to-aws-s3-using-br.md, en/upgrade-tidb-operator.md, zh/backup-to-aws-s3-using-br.md, zh/backup-to-s3.md, zh/configure-a-tidb-cluster.md
Signed-off-by: Aylei <rayingecho@gmail.com>
=> Markdown lint in github action

en/TOC.md, zh/TOC.md
Remove `TiDB Operator` from API reference doc title in TOC.
=> zh, en: update api references in toc

.github/workflows/ci.yaml, zh/configure-a-tidb-cluster.md
Add markdownlint in `ci.yaml`
- Other reference link(s): https://github.com/pingcap/docs-tidb-operator/pull/210
=> .github: add markdownlint in ci

en/deploy-on-aws-eks.md
Update Helm content in AWS deployment doc.
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/1984
=> en: update helm content in aws deployment doc

en/enable-tls-between-components.md, zh/enable-tls-between-components.md
=> zh, en: uniq CN to `TiDB` in TLS

en/api-references.md, zh/api-references.md
=> zh,en: Update the api-references link error

en/enable-tls-between-components.md, zh/enable-tls-between-components.md
=> Fix tls configuration typo

zh/maintain-a-kubernetes-node.md
=> zh: update maintain-a-kubernetes-node.md

en/maintain-a-kubernetes-node.md, zh/maintain-a-kubernetes-node.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/227
=> zh, en: fix a typo in maintain-a-kubernetes-node.md

en/restart-a-tidb-cluster.md
Add restart all component pods of tidb cluster.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/208
=> en: add restart component of tidb cluster

zh/TOC.md, zh/configure-cluster-using-tidbcluster.md, zh/deploy-on-general-kubernetes.md, zh/deploy-tiflash.md, zh/scale-a-tidb-cluster.md, zh/use-auto-failover.md
=> zh: update doc for tiflash

.github/workflows/media.yml
=> ci: update media.yml

en/enable-tls-between-components.md
This document refers to "tlsClient", when it should be "tlsCluster" for TLS between Cluster components.
=> Fixed tlsClient -> tlsCluster

zh/TOC.md, zh/pd-recover.md
=> zh: add pd-recover doc

en/TOC.md, en/backup-and-restore-using-helm-charts.md, en/backup-to-aws-s3-using-br.md, en/backup-to-s3.md, en/notes-tidb-operator-v1.1.md, en/restore-data-using-tidb-lightning.md, en/restore-from-aws-s3-using-br.md, en/restore-from-gcs.md, en/restore-from-s3.md, zh/TOC.md, zh/backup-and-restore-using-helm-charts.md, zh/backup-to-aws-s3-using-br.md, zh/backup-to-gcs.md, zh/backup-to-s3.md, zh/notes-tidb-operator-v1.1.md, zh/restore-data-using-tidb-lightning.md, zh/restore-from-aws-s3-using-br.md, zh/restore-from-gcs.md, zh/restore-from-s3.md
update doc for backup and restore
=> en, zh: update doc for backup and restore

en/TOC.md, en/pd-recover.md
Add pd-recover doc.
- This PR is translated from:  https://github.com/pingcap/docs-tidb-operator/pull/245
=> en: add pd-recover doc

zh/deploy-tiflash.md
- Other reference link(s): https://github.com/pingcap/docs-tidb-operator/pull/259
=> zh: fix typo in deploy tiflash

en/deploy-on-alibaba-cloud.md, en/deploy-on-aws-eks.md, en/deploy-on-gcp-gke.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-from-kubernetes-kind.md, en/deploy-tidb-from-kubernetes-minikube.md, en/deploy-tidb-operator.md, en/tidb-toolkit.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-on-aws-eks.md, zh/deploy-on-gcp-gke.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-from-kubernetes-kind.md, zh/deploy-tidb-from-kubernetes-minikube.md, zh/deploy-tidb-operator.md, zh/tidb-toolkit.md
update helm version and command to search chart
=> en, zh: update helm version and command to search chart

zh/deploy-on-alibaba-cloud.md, zh/deploy-on-aws-eks.md, zh/scale-a-tidb-cluster.md
update doc for tiflash on eks and ack
=> zh: update doc for tiflash on eks and ack

zh/deploy-tidb-from-kubernetes-kind.md
=> zh: simplify kind tutorial

zh/deploy-on-aws-eks.md
Fix https://github.com/pingcap/tidb-operator/issues/2368
=> zh: add doc to enable cross-zone load balancing for nlb

en/deploy-tidb-from-kubernetes-kind.md
Simplify the doc for deploying tidb using kind.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/263
=> en: simplify kind tutorial

en/deploy-tidb-from-kubernetes-kind.md
=> en: add a link in kind tutorial

en/TOC.md, en/configure-cluster-using-tidbcluster.md, en/deploy-on-general-kubernetes.md, en/deploy-tiflash.md, en/scale-a-tidb-cluster.md, en/use-auto-failover.md
Update doc for TiFlash.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/236
=> en: update doc for tiflash

zh/configure-a-tidb-cluster.md
=> zh: fix a broken link

en/configure-a-tidb-cluster.md
Fix a broken link
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/286
=> en: fix a broken link

scripts/markdownlint
Add a script to run markdownlint check locally.
=> scripts: add a script to run markdownlint check locally

en/configure-a-tidb-cluster.md, zh/configure-a-tidb-cluster.md
=> en, zh: update hostname to host

en/TOC.md, zh/TOC.md
Update toc according to the agreement.
=> en, zh: update toc

.github/workflows/ci.yaml
then we can run actions CI on special branches such as `docs-special-week`
=> trigger pull request CI on all branches

.github/workflows/assign-to-project.yml
=> .github: add workflow to auto assign to projects

en/enable-tls-between-components.md, zh/enable-tls-between-components.md
Add tikv-ctl in TLS document.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/314
=> en, zh: add tikv-ctl in tls document

zh/enable-tls-for-mysql-client.md
=> zh: refine tls document

en/backup-to-gcs.md, en/backup-to-s3.md
Update CRD backup docs with mydumper.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/273
=> en: update mydumper backup docs

zh/configure-backup.md
=> zh: fix build issue in release 1.0

en/TOC.md, zh/TOC.md
=> en, zh: fix build issues in toc

en/TOC.md, en/configure-cluster-using-tidbcluster.md, en/deploy-on-general-kubernetes.md, en/deploy-ticdc.md, en/scale-a-tidb-cluster.md, zh/configure-cluster-using-tidbcluster.md
Add TiCDC English documents.
Fix a small issue in the Chinese doc.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/298
=> en: add ticdc doc

en/enable-tls-for-mysql-client.md
Update document for separate client certificates for each component.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/275, https://github.com/pingcap/docs-tidb-operator/pull/321
=> en: separate client certificates for each component

zh/TOC.md, zh/cheat-sheet.md
=> zh: add cheat sheet

en/deploy-ticdc.md
=> en: add draft false

zh/_index.md
=> Update landing page _index.md for TiDB Operator

zh/_index.md
=> Fix _index.md

zh/_index.md
Reverts pingcap/docs-tidb-operator#350
=> Revert "Update landing page _index.md for TiDB Operator (#349)"

zh/TOC.md, zh/whats-new-in-v1.1.md
=> zh: what's new in v1.1

en/configure-tidb-binlog-drainer.md, en/tidb-cluster-chart-config.md, zh/configure-tidb-binlog-drainer.md, zh/tidb-cluster-chart-config.md
=> tidb-cluster-chart-config: fix affinity links

zh/enable-tidb-cluster-auto-scaling.md, zh/scale-a-tidb-cluster.md
Revise the scale tidbcluster document
=> zh: revise TidbCluster Scaling

en/TOC.md, zh/TOC.md
=> en, zh: add sysbench in TOC

en/monitor-using-tidbmonitor.md
Add a section in TidbMonitor to introduce how to enable Ingress.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/234
=> en: add doc for ingress in tidbmonitor

zh/configure-cluster-using-tidbcluster.md
close https://github.com/pingcap/docs-tidb-operator/issues/395
Fix error set configuration
=> Fix config setting in document

en/get-started.md
remove extra lines to fix the CI issue for https://github.com/pingcap/docs-tidb-operator/pull/402
- Other reference link(s): https://github.com/pingcap/docs-tidb-operator/pull/402
=> en: remove extra lines

en/deploy-tidb-from-kubernetes-gke.md
Fix a broken link for CustomResourceDefinition
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/402
=> en: fix a broken link for CustomResourceDefinition

zh/deploy-tidb-from-kubernetes-kind.md
=> en, zh: Update tidb-operator version to v1.1.0 in kind tutorial

zh/access-dashboard.md
Update access-dashboard document
=> zh: revise access-dashboard.md

en/enable-tidb-cluster-auto-scaling.md, en/scale-a-tidb-cluster.md
Revise the tidbcluster scaling doc.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/317
=> en: revise the tidbcluster scaling doc

zh/monitor-using-tidbmonitor.md
follow: https://github.com/pingcap/tidb-operator/pull/2738
=> zh: fix monitor

en/TOC.md, en/_index.md, en/deploy-on-general-kubernetes.md
- Update `_index.md` with the [new landing page format](https://github.com/pingcap/website-docs#landing-page-for-tidb)
- Update API docs links according to #424 
- Add a link to `en/deploy-on-general-kubernetes.md`
- This PR is translated from:  #349 
- Other reference link(s):  #424
=> en: udpate index with new format and fix links

zh/access-dashboard.md
revise access-dashboard document
=> zh: revise access-dashboard document

en/get-started.md
=> en: update get-started

en/access-dashboard.md
Add prerequisites and update sections.
Fix indent errors.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/422, https://github.com/pingcap/docs-tidb-operator/pull/432
=> en: update access-dashboard

zh/faq.md
=> zh: fix timezone

en/deploy-on-alibaba-cloud.md, en/deploy-on-aws-eks.md
Add the deployment of TiCDC in 2 deploy docs.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/363
=> en: add ticdc to ack and eks

en/get-started.md
=> en: update operator version

en/troubleshoot.md
fix the "Debugging DNS Resolution" link
=> en: fix the "Debugging DNS Resolution" link

zh/troubleshoot.md
fix a DNS debugging link
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/462
=> zh: fix a DNS debugging link

zh/_index.md
=> zh: update the API reference link

en/restore-data-using-tidb-lightning.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/369
=> en: fix indent error in secret yaml

en/tidb-scheduler.md, zh/tidb-scheduler.md
add scheduler scheduling based on customer topology
=> en, zh: add scheduler scheduling based on customer topology

en/_index.md
- Other reference link(s):  1.1 has been modified in https://github.com/pingcap/docs-tidb-operator/pull/500
=> Remove _index/ in the alias

en/configure-a-tidb-cluster.md
Fix the affinity link
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/512
=> en: fix the affinity link

zh/configure-a-tidb-cluster.md
=> zh: fix the affinity link

zh/deploy-tidb-from-kubernetes-kind.md
=> zh: add aliases for kind deployment

en/get-started.md
=> update operator version to v1.1.2 from v1.1.1

en/deploy-tidb-operator.md, en/tidb-toolkit.md, zh/tidb-toolkit.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/400
=> en: tidb opreator offline installation

.github/workflows/ci.yaml, en/notes-tidb-operator-v1.1.md, en/restore-from-s3.md, en/tidb-operator-overview.md, en/tidb-scheduler.md, en/upgrade-a-tidb-cluster.md, hack/verify-link-anchors.sh, hack/verify-links.sh, zh/backup-to-gcs-using-br.md, zh/deploy-on-aws-eks.md, zh/notes-tidb-operator-v1.1.md, zh/restore-from-gcs-using-br.md, zh/tidb-operator-overview.md, zh/upgrade-a-tidb-cluster.md
I will manually cherry-pick this PR to release-1.0.
- Other reference link(s):  https://github.com/pingcap/docs-dm/pull/146/
=> Add scripts to verify link anchors

en/deploy-on-general-kubernetes.md, en/deploy-ticdc.md, en/deploy-tidb-binlog.md, en/deploy-tiflash.md, en/initialize-a-cluster.md, en/monitor-using-tidbmonitor.md
Signed-off-by: lucklove <gnu.crazier@gmail.com>
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/420
=> en: tidb cluster offline installation

en/get-started.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-on-aws-eks.md, zh/deploy-on-gcp-gke.md, zh/deploy-on-general-kubernetes.md, zh/deploy-ticdc.md, zh/deploy-tidb-binlog.md, zh/deploy-tiflash.md, zh/upgrade-a-tidb-cluster.md
Add how to deploy enterprise tidb cluster.
=> zh: add enterprise usage

en/architecture.md, en/view-logs.md
Add aliases to files that are newly added since Jun 25
1.1: https://github.com/pingcap/docs-tidb-operator/pull/541
1.0: no new files since Jun 25
=> add 2 aliases to 2 files to avoid 404 urls in Google

en/get-started.md
remove extra line inside a code block
=> chore: update docs format

en/backup-to-gcs.md, en/backup-to-s3.md, en/restore-from-gcs.md, en/restore-from-s3.md, zh/backup-to-gcs.md, zh/backup-to-s3.md, zh/restore-from-gcs.md, zh/restore-from-s3.md
Fix https://github.com/pingcap/tidb-operator/issues/2735
=> en, zh: add note about pvc deletion

zh/configure-a-tidb-cluster.md
=> zh: fix a typo in aliases

en/configure-a-tidb-cluster.md, zh/configure-a-tidb-cluster.md
=> zh,en: fix wrong image url

.circleci/config.yml
=> chore: update pdf name

zh/configure-a-tidb-cluster.md
=> zh: fix the API doc link

zh/configure-storage-class.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/471
=> zh: update warning about deleting PVs

zh/deploy-tidb-binlog.md
document how to set tls config between drainer and upstream database
https://github.com/pingcap/tidb-operator/pull/3000
=> document how to set tls config between drainer and upstream database

en/access-dashboard.md, en/access-tidb.md, en/architecture.md, en/backup-to-aws-s3-using-br.md, en/backup-to-gcs.md, en/backup-to-s3.md, en/benchmark-sysbench.md, en/configure-a-tidb-cluster.md, en/configure-storage-class.md, en/deploy-on-alibaba-cloud.md, en/deploy-on-aws-eks.md, en/deploy-on-gcp-gke.md, en/deploy-on-general-kubernetes.md, en/deploy-ticdc.md, en/deploy-tidb-binlog.md, en/deploy-tidb-operator.md, en/deploy-tiflash.md, en/destroy-a-tidb-cluster.md, en/enable-admission-webhook.md, en/enable-tidb-cluster-auto-scaling.md, en/enable-tls-between-components.md, en/enable-tls-for-mysql-client.md, en/exceptions.md, en/faq.md, en/get-started.md, en/monitor-using-tidbmonitor.md
Fix some obvious errors in the existing files.
=> en: improve format and fix errors in existing files

en/deploy-on-aws-eks.md, en/deploy-on-gcp-gke.md, zh/deploy-on-aws-eks.md, zh/deploy-on-gcp-gke.md
=> en, zh: do not recommend local ssds for tikv storage

en/TOC.md, en/backup-and-restore-using-helm-charts.md, en/backup-to-aws-s3-using-br.md, en/backup-to-gcs.md, en/backup-to-s3.md, en/notes-tidb-operator-v1.1.md, en/restore-data-using-tidb-lightning.md
Replace Mydumper with Dumpling in backup docs.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/562
=> en: replace Mydumper with Dumpling

en/backup-to-gcs-using-br.md, en/backup-to-s3.md
update indent and add closed tag for `<code>`
=> chore: update list indent and make tag closed

en/get-started.md
=> en: fix aliases in get-started

en/get-started.md
=> en: add a slash in aliases

.github/pull_request_template.md
=> .github: add cherry-pick checklist in pr template

en/access-tidb.md
=> en: fix a dead link

en/deploy-tidb-binlog.md, zh/deploy-tidb-binlog.md
=> en, zh: get rid of evil words

en/backup-to-aws-s3-using-br.md, en/backup-to-gcs-using-br.md, en/backup-to-gcs.md, en/backup-to-s3.md, en/deploy-on-aws-eks.md
- Add a section about how to delete the backup CR (https://github.com/pingcap/docs-tidb-operator/pull/566, https://github.com/pingcap/docs-tidb-operator/pull/591)
- Add a step in deploy-on-aws-eks.md (https://github.com/pingcap/docs-tidb-operator/pull/523)
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/566, https://github.com/pingcap/docs-tidb-operator/pull/591, https://github.com/pingcap/docs-tidb-operator/pull/523
=> en: add how to delete backup cr

en/_index.md, zh/_index.md
[What's New in v1.1](https://docs.pingcap.com/tidb-in-kubernetes/stable/whats-new-in-v1.1) is an important doc for users of earlier versions. I think we should include it in the landing page.
=> en, zh: update index to include what's new in v1.1

en/get-started.md, zh/get-started.md
Add an alias to fix a dead link.
=> Add an alias to fix a dead link

en/access-tidb.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/535
=> en: stop tidb gracefully

en/deploy-ticdc.md, en/enable-tls-between-components.md
Add a section to enable TLS for TiCDC.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/590
=> en: enable tls for ticdc

en/enable-tidb-cluster-auto-scaling.md, zh/enable-tidb-cluster-auto-scaling.md
Update the first paragraph of `enable-tidb-cluster-auto-scaling.md` to include elastic scheduling.
=> en, zh: update wording to include elastic scheduling

en/whats-new-in-v1.1.md, zh/whats-new-in-v1.1.md
=> en,zh: update what's new title

en/get-started.md, zh/get-started.md
=> Add aliases to fix 2 dead links

zh/TOC.md, zh/deploy-tidb-enterprise-edition.md
According to some users it's hard to find how to deploy tidb cluster enterprise edition through tidb-operator. So I add a single document to describe how to deploy enterprise edition tidb cluster.
=> zh: add single page to describe enterprise edition deployment

en/TOC.md, en/deploy-tidb-enterprise-edition.md
Add a single document to describe how to deploy enterprise edition TiDB cluster.
- This PR is translated from:  https://github.com/pingcap/docs-tidb-operator/pull/638
=> en: add single page to describe enterprise edition deployment

zh/get-started.md
Close https://github.com/pingcap/docs-tidb-operator/issues/646
=> zh: remove an extra line in code block

zh/deploy-on-aws-eks.md
=> zh: simplify AWS/EKS deployment guide

zh/deploy-on-aws-eks.md
=> cherry-pick #584 to release-1.1: zh: simplify AWS/EKS deployment guide

zh/enable-tls-between-components.md
=> zh: update tls doc for tiflash

en/deploy-on-aws-eks.md
=> en: update instance type for tikv

en/enable-tls-between-components.md
Update docs to include TLS support for TiFlash.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/654
=> en: update tls doc for tiflash

en/backup-to-aws-s3-using-br.md, en/backup-to-gcs-using-br.md, en/backup-to-gcs.md, en/backup-to-s3.md, en/deploy-failures.md, en/restore-from-aws-s3-using-br.md, en/restore-from-gcs-using-br.md, en/restore-from-gcs.md, en/restore-from-s3.md, zh/enable-tls-between-components.md
- Add the debug section for backup & restore files.
- Comment `storageClassName` by default.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/639
=> en: add debug section for backup & restore

en/get-started.md, zh/deploy-on-aws-eks.md, zh/deploy-on-gcp-gke.md, zh/initialize-a-cluster.md, zh/restore-from-aws-s3-using-br.md
Add 7 aliases to fix dead links
=> Add 7 aliases to fix dead links

en/deploy-tidb-binlog.md
Add sections to describe how to take pump/drainer offline.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/655
=> en: add sections for taking binlog offline

en/access-dashboard.md, en/access-tidb.md, en/advanced-statefulset.md, en/backup-to-aws-s3-using-br.md, en/backup-to-gcs-using-br.md, en/backup-to-gcs.md, en/backup-to-s3.md, en/configure-a-tidb-cluster.md, en/deploy-on-gcp-gke.md, en/deploy-on-general-kubernetes.md, en/deploy-tidb-binlog.md, en/deploy-tidb-enterprise-edition.md, en/enable-tls-between-components.md, en/enable-tls-for-mysql-client.md, en/monitor-using-tidbmonitor.md, en/notes-tidb-operator-v1.1.md, en/pd-recover.md, en/restart-a-tidb-cluster.md, en/restore-data-using-tidb-lightning.md, en/restore-from-aws-s3-using-br.md, en/restore-from-gcs-using-br.md, en/restore-from-gcs.md, en/restore-from-s3.md, en/upgrade-a-tidb-cluster.md
- Bump TiDB version to v4.0.4
- Add privilege demands for backup&restore db accounts
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/656
=> en: bump tidb version to 4.0.4

zh/deploy-on-gcp-gke.md
cherry-pick #672 into release-1.1.
=> release-1.1: zh: simplify gcp/gke deployment guide (#672)

en/monitor-using-tidbmonitor.md, zh/monitor-using-tidbmonitor.md
Fix https://github.com/pingcap/tidb-operator/issues/3221
=> en,zh: add note about cluster name in monitor

zh/configure-a-tidb-cluster.md
=> zh: add recommended configurations

.github/workflows/ci.yaml, en/backup-to-aws-s3-using-br.md, en/backup-to-gcs.md, en/backup-to-s3.md, en/deploy-on-gcp-gke.md, hack/check-tags.py, zh/backup-to-s3.md
1. only check .md files in zh/ and en/ folders
2. report unclosed tags (might be caused by unclosed inline code)
=> add ci job to check unclosed tags; fix some inline codes

zh/deploy-on-aws-eks.md, zh/deploy-on-gcp-gke.md
Some improvements from https://docs.google.com/document/d/1vmKXYPwzXzxuygH0iUBjEKioNHB4pewvLyAFGkivz7U.
=> zh: improvements from Queeny Test

en/configure-a-tidb-cluster.md
Add three recommended configs for cluster deployment.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/680
=> en: add recommended configs for cluster deployment

zh/use-auto-failover.md
=> Modify the description of tikv scale-in

en/deploy-tiflash.md, zh/deploy-tiflash.md
=> en, zh: add config notes for tiflash

en/configure-a-tidb-cluster.md, en/enable-tls-between-components.md, zh/configure-a-tidb-cluster.md, zh/enable-tls-between-components.md
Update doc for https://github.com/pingcap/tidb-operator/pull/3282, https://github.com/pingcap/tidb-operator/pull/3248
=> en, zh: update doc for pd-ctl and tikv-ctl when tls enabled

en/use-auto-failover.md, zh/use-auto-failover.md
=> en, zh: update failover recover procedure for tikv and tiflash

en/cheat-sheet.md, en/configure-storage-class.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/configure-storage-class.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
Update tidb-operator chart version to v1.1.5.
=> zh, en/: update tidb-operator chart version to v1.1.5

zh/backup-to-aws-s3-using-br.md, zh/backup-to-gcs-using-br.md, zh/restore-from-aws-s3-using-br.md, zh/restore-from-gcs-using-br.md
close https://github.com/pingcap/docs-tidb-operator/issues/703
Some parameters are not explained in the backup and restore docs, e.g. the parameters in spec.br, we'd better check all of the backup and restore docs to make sure that all of the parameters in the CR are explained.
=> zh/: update br usage documents for aws and gcs

en/access-dashboard.md, en/access-tidb.md, en/advanced-statefulset.md, en/backup-to-aws-s3-using-br.md, en/backup-to-gcs-using-br.md, en/backup-to-gcs.md, en/backup-to-s3.md, en/configure-a-tidb-cluster.md, en/deploy-on-general-kubernetes.md, en/deploy-tidb-binlog.md, en/deploy-tidb-enterprise-edition.md, en/enable-tls-between-components.md, en/enable-tls-for-mysql-client.md, en/monitor-using-tidbmonitor.md, en/notes-tidb-operator-v1.1.md, en/pd-recover.md, en/restart-a-tidb-cluster.md, en/restore-data-using-tidb-lightning.md, en/restore-from-aws-s3-using-br.md, en/restore-from-gcs-using-br.md, en/restore-from-gcs.md, en/upgrade-a-tidb-cluster.md
- Update tableFilter usage in backup and restore files.
- Bump tidb to 4.0.6.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/699
=> en: update tableFilter usage and bump tidb to 4.0.6

zh/deploy-tidb-binlog.md
close https://github.com/pingcap/docs-tidb-operator/issues/728
update how to change tidb configs when we try to remove pump node
=> zh: update how to change tidb configs when we try to remove pump node

zh/deploy-tidb-binlog.md
supplement of https://github.com/pingcap/docs-tidb-operator/pull/730. update pump doc to change warning to step
=> zh: update pump doc to change warning to step

en/deploy-tidb-binlog.md, zh/deploy-tidb-binlog.md
- Add a step for removing Pump nodes.
- Update Chinese format to use ordered lists for steps.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/730, https://github.com/pingcap/docs-tidb-operator/pull/735
=> en, zh: add a step for removing Pump nodes

.github/workflows/stale.yaml
Add a message before closing a stale issue:
> This issue will be closed because it has been open for 75 days with no activity. If you still have any question about this issue, feel free to reopen it or create a new one.
- Other reference link(s):  https://github.com/actions/stale
=> .github: modify the action to label stale issues

zh/deploy-heterogeneous-tidb-cluster.md
This is a follow-up PR of https://github.com/pingcap/docs-tidb-operator/pull/747#issuecomment-701128889
- This PR is translated from:  https://github.com/pingcap/docs-tidb-operator/pull/747
=> zh: update steps for heterogeneous cluster deployment

en/TOC.md, en/roadmap.md, zh/TOC.md, zh/roadmap.md
=> en, zh: add roadmap

zh/configure-a-tidb-cluster.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-on-aws-eks.md, zh/deploy-on-gcp-gke.md, zh/deploy-tiflash.md
=> zh: update for logs of tiflash

en/configure-a-tidb-cluster.md, en/deploy-tidb-binlog.md, zh/configure-a-tidb-cluster.md, zh/deploy-tidb-binlog.md
- Support passing raw toml config for tiflash ([#3355](https://github.com/pingcap/tidb-operator/pull/3355), [@july2993](https://github.com/july2993))
- Support passing raw toml config for tikv/pd ([#3342](https://github.com/pingcap/tidb-operator/pull/3342), [@july2993](https://github.com/july2993))
- Support passing raw toml config for tidb ([#3327](https://github.com/pingcap/tidb-operator/pull/3327), [@july2993](https://github.com/july2993))
- Support passing raw toml config for pump ([#3312](https://github.com/pingcap/tidb-operator/pull/3312), [@july2993](https://github.com/july2993))
=> en, zh: Add docs about passing raw TOML config

en/notes-tidb-operator-v1.1.md, zh/notes-tidb-operator-v1.1.md
=> en, zh: update notes for tidb-cluster chart

en/cheat-sheet.md, en/configure-storage-class.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/configure-storage-class.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
run:
find . -type file | xargs gsed -i "s/v1\.1\.5/v1\.1\.6/g"
check and revert some wrongly update
ref #717 
=> zh, en: update tidb-operator chart version to v1.1.6

zh/TOC.md
Add migrate-tidb-to-kubernetes.md to TOC.
- Other reference link(s): https://github.com/pingcap/docs-tidb-operator/pull/704
=> zh: update toc

en/releases/release-1.1.6.md, zh/releases/release-1.1.6.md
=> en, zh: update release notes for v1.1.6

en/TOC.md, en/migrate-tidb-to-kubernetes.md, zh/migrate-tidb-to-kubernetes.md
- Add an English doc for migrating tidb to k8s.
- Add TiUP scaling in steps to the Chinese doc.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/704
=> en, zh: add a doc for migrating tidb to k8s

zh/releases/release-1.1.0-rc.1.md
Add v1.1.0-rc.1 release notes. 
- Other reference link(s):  #674
=> zh: add v1.1-rc.1 release notes

.github/workflows/stale.yaml
Issues with `good-first-issue` and `help-wanted` labels will not be closed by the action.
=> .github: add 2 exempt issue labels

en/monitor-using-tidbmonitor.md
Doc update for monitoring multiple TiDB clusters with one TidbMonitor.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/757
=> en: Doc update for monitoring multiple TiDB clusters with one TidbMonitor

en/migrate-tidb-to-kubernetes.md
Trailing whitespace will break JSX rule.
=> fix: trim trailing whitespace

zh/deploy-failures.md, zh/deploy-tidb-enterprise-edition.md, zh/restart-a-tidb-cluster.md, zh/scale-a-tidb-cluster.md
delete docs about using kubectl apply to update tidb cluster configurations
=> zh: delete docs about using kubectl apply to update tidb cluster configurations

en/deploy-failures.md, en/deploy-tidb-enterprise-edition.md, en/restart-a-tidb-cluster.md, en/scale-a-tidb-cluster.md
Delete docs about using kubectl apply to update tidb cluster configurations.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/794
=> en: delete docs about using kubectl apply to update tidb cluster configurations

en/restart-a-tidb-cluster.md
Forgot to accept the comment (https://github.com/pingcap/docs-tidb-operator/pull/797#discussion_r513144581).
=> en: fix a sentence

en/TOC.md, en/access-tidb.md, en/deploy-tidb-dm.md, en/enable-tls-for-dm.md
1. Add how to deploy `dmcluster` and how to start a dm replication task.
2. Add how to enable tls in dm.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/742
=> en: add dmcluster usage document

en/deploy-tiflash.md
remove dead link for deploying tiflash
- This PR is translated from:  https://github.com/pingcap/docs-tidb-operator/pull/806
=> en: remove dead link for tiflash

en/backup-and-restore-using-helm-charts.md, en/configure-storage-class.md, zh/logs-collection.md, zh/upgrade-a-tidb-cluster.md, zh/use-auto-failover.md
Add 4 aliases to fix broken links.
=> Add 4 aliases to fix broken links

.github/workflows/link-check.yaml
=> filter one external link to pass ci check

README.md
Add Google Translate links of French, Japanese and Korean to the README file.
=> readme: add google translate links of French, Japanese, Korean

en/migrate-tidb-to-kubernetes.md
fix `TidbCluster` parameter `pdAddresses`.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/820
=> en: fix pdAddresses

en/releases/release-1.1.6.md, zh/releases/release-1.1.6.md
=> en, zh: update release note for v1.1.6

en/cheat-sheet.md, en/configure-storage-class.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/configure-storage-class.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
bump tidb operator charts version to v1.1.7
- Other reference link(s):  #3495
None
=> en, zh: bump tidb operator charts version to v1.1.7

zh/releases/release-1.1.0-rc.4.md
=> releases: fix full-width hash sign resulting in lint failure

en/configure-a-tidb-cluster.md, en/configure-storage-class.md, en/deploy-tidb-operator.md, en/prerequisites.md
Improve self-hosted k8s deployment.
- This PR is translated from:  https://github.com/pingcap/docs-tidb-operator/pull/804
=> en: Improve self-hosted k8s deployment

en/deploy-on-aws-eks.md, zh/deploy-on-aws-eks.md
Improve the format and readability of deploy-on-aws-eks.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/802
=> en: improve deploy on aws eks

en/get-started.md, zh/get-started.md
Refactor get-started.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/801
=> en: refactor get-started

en/deploy-tidb-binlog.md
- fix helm 2/3 command
- add attention block in pump nodes remove section
- This PR is translated from:  https://github.com/pingcap/docs-tidb-operator/pull/807
=> en: fix deploy-tidb-binlog.md

en/logs-collection.md, en/use-tkctl.md, zh/configure-a-tidb-cluster.md, zh/restore-data-using-tidb-lightning.md
Add 3 aliases to fix broken links.
=> Add 3 aliases to fix broken links

en/configure-a-tidb-cluster.md, zh/configure-a-tidb-cluster.md
Add multiple pv doc.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/846
=> en: mount multiple pv for tidbcluster

en/deploy-on-gcp-gke.md
Improve deploy-on-gcp-gke.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/803
=> en: improve deploy-on-gcp-gke

.github/pull_request_template.md
Add CLA signing request in the pull request template and simplify the content.
=> add guide of signing CLA

.github/pull_request_template.md
The old link returns 404.
Suggest using the documentation contributing guide.
=> .github: update contributing guide link

en/restore-from-s3.md, zh/restore-from-s3.md
Fix the wrong yaml example of restore from s3.
=> s3: fix restore yaml example

en/use-tkctl.md, zh/use-tkctl.md
=> en, zh: update tkctl debug usage

en/configure-a-tidb-cluster.md, en/deploy-tiflash.md, zh/configure-a-tidb-cluster.md, zh/deploy-tiflash.md
fix tiflash deployment example
Fixes https://github.com/pingcap/tidb-operator/issues/3563
None
=> en, zh: fix tiflash deployment example

en/deploy-on-aws-eks.md, zh/deploy-on-aws-eks.md
=> en, zh: update aws deploy doc

zh/configure-a-tidb-cluster.md
Fix  storageVolumes doc yaml.
https://github.com/pingcap/tidb-operator/pull/3586
=> zh: fix tidb storageVolumes doc

zh/configure-a-tidb-cluster.md
Fix storageVolumes demo yaml configuration.
=> fix storageVolumes demo config error

en/deploy-ticdc.md, zh/deploy-ticdc.md
Update `cdc cli capture list` output.
Deploy ticdc with `replica:3`, but the `cdc cli capture list` only display two instances. I update the `cdc cli capture list` output.
=> Update cdc cli capture list output

en/monitor-using-tidbmonitor.md, zh/monitor-using-tidbmonitor.md
=> remove procedure about monitoring multiple clusters

en/configure-a-tidb-cluster.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/909, https://github.com/pingcap/docs-tidb-operator/pull/914
=> en: fix tidb and pd storageVolumes config

en/TOC.md, en/use-auto-failover.md, zh/use-auto-failover.md
fix #492, change catalog name
fix #790, add how to disable auto failover and failover notes
=> add disable auto failover

en/destroy-a-tidb-cluster.md, en/enable-tidb-cluster-auto-scaling.md, en/scale-a-tidb-cluster.md, zh/monitor-using-tidbmonitor.md
Fix some typos and refine language
=> fix typos and refine language

en/TOC.md, en/releases/release-1.1.9.md, zh/TOC.md, zh/releases/release-1.1.9.md
Add release notes for TiDB-Operator v1.1.8
- https://github.com/pingcap/tidb-operator/issues/3656
=> en, zh: add release notes for 1.1.9

zh/enable-tls-between-components.md
add hosts for TiKV-Importer TLS because we use the headless service to pull metrics now.
- Other reference link(s): https://github.com/pingcap/tidb-operator/pull/3631
=> zh: add hosts for TiKV-Importer TLS

zh/restore-data-using-tidb-lightning.md
Add the doc about Ad-hoc mode for TiDB-Lightning helm chart.
Close #862 
=> zh: add the doc about Ad hoc mode for TiDB-Lightning

en/scale-a-tidb-cluster.md, zh/scale-a-tidb-cluster.md
=> fix var name

en/upgrade-tidb-operator.md
Add a command to update helm repo before upgrading TiDB Operator.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/943
=> en: add a command to update helm repo

en/restore-data-using-tidb-lightning.md
Add contents about TiDB Lightning backend.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/963
=> en: add tidb lightning backend info

zh/configure-a-tidb-cluster.md
Add a note about update PD config
close #959
=> zh: add a note about update PD config

en/cheat-sheet.md, en/configure-storage-class.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/configure-storage-class.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
bump tidb operator charts version to v1.1.9
```
find . -type f | xargs sed -i "s/v1.1.8/v1.1.9/g"
```
ref #939
- https://github.com/pingcap/tidb-operator/issues/3656
=> en, zh: bump TiDB Operator charts version to v1.1.9

en/TOC.md, en/backup-and-restore-using-helm-charts.md, en/backup-to-pv-using-br.md, en/restore-from-pv-using-br.md, zh/TOC.md, zh/backup-and-restore-using-helm-charts.md, zh/backup-to-gcs-using-br.md, zh/backup-to-pv-using-br.md, zh/restore-from-pv-using-br.md
Add introduction docs about how to use `Backup` & `Restore` with BR to do backup/restore job, with a Persisten Volume(PV) as the storage backend. The docs use NFS as an example PV type.
The corresponding feature is supported in TiDB Operator v1.1.8 release recently.
- implemented in https://github.com/pingcap/tidb-operator/pull/3517
=> en, zh: Add docs about using BR to backup/restore with PV(NFS as an example)

zh/deploy-on-alibaba-cloud.md, zh/deploy-on-aws-eks.md, zh/deploy-on-gcp-gke.md, zh/deploy-tidb-operator.md
link docs for deployment. close #486.
=> zh: link deployment docs

zh/deploy-tiflash.md
Add “Remove TiFlash” section in `deploy-tiflash.md`.
Fix #537.
=> zh; Add section 'Remove TiFlash' in deploy-tiflash.md

zh/restore-data-using-tidb-lightning.md
Add contents about troubleshoot for TiDB Lightning.
Close #926.
=> zh: add contents about troubleshoot for TiDB Lightning

zh/configure-a-tidb-cluster.md
- Add contents about `hostNetwork`. close #695
- Refine the structure mentioned in https://github.com/pingcap/docs-tidb-operator/pull/998#discussion_r551297751.
=> zh: add contents about hostNetwork

en/maintain-a-kubernetes-node.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/973
=> en: add --wait=false when deleting pvc in k8s

en/tidb-toolkit.md, zh/tidb-toolkit.md
=> update doc for tikv-ctl

en/configure-a-tidb-cluster.md, en/deploy-on-alibaba-cloud.md, en/deploy-on-aws-eks.md, en/deploy-on-gcp-gke.md, en/deploy-tidb-operator.md
- add a note about pd config
- link deployment docs
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/972, https://github.com/pingcap/docs-tidb-operator/pull/983
=> en: update pd config; link deployment docs

en/enable-tls-between-components.md, en/enable-tls-for-mysql-client.md, en/restore-data-using-tidb-lightning.md
- Add contents for enabling tidb lightning tls (#922)
- Add tidb lightning troubleshooting (#970)
- Add tikv-importer tls host (#942)
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/922, https://github.com/pingcap/docs-tidb-operator/pull/970, https://github.com/pingcap/docs-tidb-operator/pull/942
=> en: add contents for enabling tidb lightning tls and troubleshooting

zh/TOC.md, zh/backup-and-restore-using-helm-charts.md, zh/cheat-sheet.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-binlog.md, zh/deploy-tidb-operator.md, zh/destroy-a-tidb-cluster.md, zh/enable-tls-between-components.md, zh/migrate-to-helm3.md, zh/recover-deleted-cluster.md, zh/restore-data-using-tidb-lightning.md, zh/roadmap.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
- add the doc about migrating from Helm2 to Helm3
- update commands for Helm3
close #869 
=> zh: add the doc about migrating to Helm3; update commands for Helm3

zh/enable-tidb-cluster-auto-scaling.md
=> zh: update auto-scaling doc for master branch

en/TOC.md, en/backup-and-restore-using-helm-charts.md, en/cheat-sheet.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-binlog.md, en/deploy-tidb-operator.md, en/destroy-a-tidb-cluster.md, en/enable-tls-between-components.md, en/migrate-to-helm3.md, en/recover-deleted-cluster.md, en/restore-data-using-tidb-lightning.md, en/roadmap.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md
- Add the doc about migrating to helm 3
- Update commands for helm 3
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1014
=> en: add the doc about migrating to helm 3

en/configure-storage-class.md
- Refine contents about local-storage.
- close #418 because it can't be reproduced.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/996
=> en: refine contents about local-storage

en/access-tidb.md, en/configure-a-tidb-cluster.md
According to issue: #911
- This PR is translated from:  https://github.com/pingcap/docs-tidb-operator/pull/929
=> en: Add content about spec.tidb.service in config-a-tidb-cluster.md

.github/workflows/stale.yaml
=> .github: update stale action version

en/deploy-tiflash.md, zh/deploy-tiflash.md
=> update doc for adding another disk for tiflash

en/enable-tidb-cluster-auto-scaling.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1049
=> en: update auto-scaling doc for tidb 5.0

en/cheat-sheet.md, en/deploy-on-alibaba-cloud.md, en/deploy-on-aws-eks.md, en/deploy-on-gcp-gke.md, en/deploy-tidb-binlog.md, en/deploy-tidb-operator.md, en/destroy-a-tidb-cluster.md, en/prerequisites.md, en/recover-deleted-cluster.md, en/restore-data-using-tidb-lightning.md, en/tidb-toolkit.md, zh/cheat-sheet.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-on-aws-eks.md, zh/deploy-on-gcp-gke.md, zh/deploy-tidb-binlog.md, zh/deploy-tidb-operator.md, zh/destroy-a-tidb-cluster.md, zh/prerequisites.md, zh/recover-deleted-cluster.md, zh/restore-data-using-tidb-lightning.md, zh/tidb-toolkit.md
fix the `uninstall` command for Helm 3
- Other reference link(s):  #1014
=> zh, en: fix uninstall command for Helm 3

en/prerequisites.md, zh/prerequisites.md
fix the format of a table
- Other reference link(s):  #1073
=> zh, en: fix table format

zh/backup-to-gcs.md, zh/configure-storage-class.md, zh/deploy-on-aws-eks.md, zh/monitor-a-tidb-cluster.md, zh/use-tkctl.md
Add 5 aliases to fix broken links
=> Add 5 aliases to fix broken links

en/TOC.md, en/deploy-multiple-tidb-operator.md, zh/TOC.md, zh/deploy-multiple-tidb-operator.md
=> en, zh: add multiple tidb-operator doc to release-1.1

en/TOC.md, en/releases/release-1.1.10.md, zh/TOC.md, zh/releases/release-1.1.10.md
=> add release notes for v1.1.10

en/deploy-tidb-operator.md
fix create a namespace for < Helm 3.2.0
- This PR is translated from:  https://github.com/pingcap/docs-tidb-operator/pull/1094
=> en: fix create a namespace for Helm 3

en/benchmark-sysbench.md, zh/backup-to-gcs.md, zh/backup-to-s3.md, zh/restore-data-using-tidb-lightning.md
Add 4 aliases to filter broken links
=> Add 4 aliases to filter broken links

en/configure-a-tidb-cluster.md, en/logs-collection.md, zh/logs-collection.md
Support configuring PV for slow logs.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1079
=> en: support slowlog PV config

zh/backup-to-gcs.md
Use ordered list and indentation.
- Other reference link(s): https://github.com/pingcap/docs-tidb-operator/blob/master/en/backup-to-gcs.md
=> zh: fix format

en/deploy-on-aws-eks.md, en/deploy-on-gcp-gke.md, zh/deploy-on-aws-eks.md, zh/deploy-on-gcp-gke.md
Rephrase local storage sections to recommend NOT to use local storage in production.
=> en, zh: recommend not to use local storage in production

en/releases/release-1.1.10.md, zh/releases/release-1.1.10.md
Fix https://github.com/pingcap/tidb-operator/issues/3828
=> en, zh: update release notes for v1.1.10

en/deploy-tidb-cluster-across-multiple-kubernetes.md
=> en: remove extra spaces and test TiChi

en/advanced-statefulset.md, en/backup-to-aws-s3-using-br.md, en/backup-to-gcs-using-br.md, en/backup-to-gcs.md, en/backup-to-pv-using-br.md, en/backup-to-s3.md, en/deploy-heterogeneous-tidb-cluster.md, en/deploy-on-aws-eks.md, en/deploy-tidb-operator.md, en/deploy-tiflash.md, en/enable-tls-between-components.md, en/initialize-a-cluster.md, en/migrate-tidb-to-kubernetes.md, zh/advanced-statefulset.md, zh/backup-to-gcs-using-br.md, zh/backup-to-pv-using-br.md, zh/deploy-heterogeneous-tidb-cluster.md, zh/deploy-on-aws-eks.md, zh/deploy-tidb-operator.md, zh/enable-tls-between-components.md, zh/initialize-a-cluster.md
=> Fix format error in "copyable" codeblocks and other type error

en/TOC.md, en/canary-upgrade-tidb-operator.md, en/deploy-multiple-tidb-operator.md
Add doc for canary upgrade tidb operator.
**FOLLOW-UP:**
> I'll remove v1.1-version-specific description from master later.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1123
=> en: add doc for canary upgrade tidb operator

en/releases/release-1.2.0-beta.1.md, zh/releases/release-1.2.0-beta.1.md
Add release notes for TiDB-Operator v1.2.0-alpha.1
- pingcap/tidb-operator#3897
=> en, zh: add release notes for v1.2.0-beta.1

en/TOC.md, zh/TOC.md
=> Fix release note TOC for v1.2.0-beta.1

en/releases/release-1.2.0-beta.1.md, zh/releases/release-1.2.0-beta.1.md
=> Add rolling upgrade notice for v1.2.0-beta.1

en/TOC.md, en/releases/release-1.1.12.md, zh/TOC.md, zh/releases/release-1.1.12.md
=> en, zh: add release notes for v1.1.12

en/deploy-tidb-operator.md, zh/deploy-tidb-operator.md
update docs about configure namespace scoped TiDB operator. ref https://github.com/pingcap/tidb-operator/pull/3896
=> zh, en: update docs about configure namespace scoped TiDB operator

en/deploy-tidb-dm.md, en/enable-tls-for-dm.md, zh/deploy-tidb-dm.md, zh/enable-tls-for-dm.md
- update `discovery` for DmCluster, ref https://github.com/pingcap/tidb-operator/pull/3914
- update the DM image version
=> zh, en: update docs for DM

en/configure-tidb-binlog-drainer.md, en/deploy-tidb-binlog.md, zh/configure-tidb-binlog-drainer.md, zh/deploy-tidb-binlog.md
fix `initialCommitTs` for drainer
=> zh, en: fix initialCommitTs for drainer

en/get-started.md
explain what `tc` means
```
$ kubectl api-resources | awk '/NAME/ { print } /^tidb/ { print }'
NAME                              SHORTNAMES   APIVERSION                             NAMESPACED   KIND
tidbclusterautoscalers            ta           pingcap.com/v1alpha1                   true         TidbClusterAutoScaler
tidbclusters                      tc           pingcap.com/v1alpha1                   true         TidbCluster
tidbinitializers                  ti           pingcap.com/v1alpha1                   true         TidbInitializer
tidbmonitors                      tm           pingcap.com/v1alpha1                   true         TidbMonitor
```
=> get-started: explain what `tc` means

en/_index.md, en/tidb-operator-overview.md
TiDB v5.0 wasn't included in the list of supported versions
=> Include TiDB v5.0 in supported versions

en/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-from-kubernetes-gke.md
refine docs for deploying TiDB on GKE
=> zh, en: refine docs for deploying TiDB on GKE

en/get-started.md, zh/get-started.md
Part of this issue: https://github.com/pingcap/docs-tidb-operator/issues/1140
> Test if `auto-cc` works.
=> en, zh: add what's next for get-started.md

zh/_index.md, zh/get-started.md, zh/tidb-operator-overview.md
Add TiDB v5.0 to the supported versions
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1171, https://github.com/pingcap/docs-tidb-operator/pull/1173
=> zh: Include TiDB v5.0 in supported versions #1171

en/enable-tls-between-components.md, zh/enable-tls-between-components.md
Fix https://github.com/pingcap/docs-tidb-operator/issues/1105
Proposing this correlation, which is easy to maintain when docs-tidb-operator checks out `release-1.2` branch:
- TiDB Operator `dev` -> TiDB `stable`
- TiDB Operator `1.1` -> TiDB `v4.0`
=> en,zh: update linked docs version in tls

en/backup-to-pv-using-br.md, en/configure-a-tidb-cluster.md, zh/backup-to-pv-using-br.md, zh/configure-a-tidb-cluster.md
ref
https://docs.pingcap.com/tidb-in-kubernetes/dev/release-1.1.8#new-features
Support arbitrary Volume and VolumeMount for PD, TiDB, TiKV, TiFlash,
Backup and Restore, which enables using NFS or any other
kubernetes supported volume source for backup/restore workflow
(#3517, @dragonly
=> en, zh: add clarify for additionalVolumeMounts

zh/get-started.md
translate get-started: add alias for kubectl in minikube #1172
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1172
=> zh: get-started: add alias for kubectl in minikube #1172

en/TOC.md, en/releases/release-1.2.0-beta.2.md, zh/TOC.md, zh/releases/release-1.2.0-beta.2.md
add release notes for v1.2.0-beta.2
=> en, zh: add release notes for v1.2.0-beta.2

en/cheat-sheet.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
Bump Operator to v1.1.12
ref #1162
Run commands:
```sh
find . -type f | xargs sed -i "s/v1.2.0-beta.1/v1.2.0-beta.2/g"
```
=> en, zh: Bump Operator to v1.2.0-beta.2

en/TOC.md, en/_index.md, en/configure-a-tidb-cluster.md, en/containers-run-as-non-root-user.md, en/deploy-tidb-dm.md, en/tidb-scheduler.md, zh/TOC.md, zh/_index.md, zh/configure-a-tidb-cluster.md, zh/containers-run-as-non-root-user.md, zh/deploy-tidb-dm.md, zh/tidb-scheduler.md
https://github.com/pingcap/tidb-operator/pull/3937
https://github.com/pingcap/tidb-operator/pull/3909
=> en, zh: add docs of topology spread constraints and security context

en/access-dashboard.md, zh/access-dashboard.md
add some clarify for dashboard
=> en, zh: add some clarify for dashboard

en/configure-a-tidb-cluster.md, zh/configure-a-tidb-cluster.md
add clarify for storageVolumes
=> en, zh: add clarify for storageVolumes

en/configure-a-tidb-cluster.md, zh/configure-a-tidb-cluster.md
explan TidbCluster `spec.discovery`
- [*] master (the latest development version)
- [*] Change aliases
=> en, zh: explain TidbCluster spec.discovery

en/configure-a-tidb-cluster.md, zh/configure-a-tidb-cluster.md
Add evict tikv leader timeout part
fix https://github.com/pingcap/docs-tidb-operator/issues/1204
=> en, zh: Add evict tikv leader timeout part

zh/faq.md
=> zh: add faq about data reliability

en/upgrade-tidb-operator.md, zh/upgrade-tidb-operator.md
en, zh: add upgrade TiDB Operator offline
- [* ] master (the latest development version)
- This PR is translated from: #1152
- [* ] Change aliases
=> en, zh: add upgrade TiDB Operator offline

en/faq.md
Add a question and answer about data reliability
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1206
=> en: add faq about data reliability #1206

en/access-dashboard.md, en/deploy-on-aws-eks.md
- Add more details about accessing TiDB with an nlb with internal scheme
- Link to info about using TiDB Dashboard
- Update info about TiDB Dashboard with Kubernetes
- https://github.com/pingcap/tidb-operator/pull/3974
- https://github.com/pingcap/tidb-operator/issues/3941
=> en: Update info on EKS and dashboard access

en/upgrade-a-tidb-cluster.md, en/upgrade-tidb-operator.md
=> en: update notes

zh/cheat-sheet.md, zh/deploy-tidb-binlog.md, zh/destroy-a-tidb-cluster.md, zh/restore-data-using-tidb-lightning.md, zh/restore-from-gcs.md, zh/restore-from-s3.md, zh/tidb-toolkit.md
Fix https://github.com/pingcap/docs-tidb-operator/issues/1213
=> zh: improve the doc of tidb-lightning

zh/deploy-tidb-dm.md, zh/enable-tls-for-dm.md
update docs about data mount path for DM-worker
=> zh: update docs about data mount path for DM-worker

zh/backup-to-s3.md, zh/deploy-on-aws-eks.md
- Use `tidb-cluster` as namespace instead of `test1`.
This matches the namespace created by
https://docs.pingcap.com/tidb-in-kubernetes/stable/deploy-on-aws-eks#create-namespace
- Change link to raw version of `backup-rbac.yaml` and directly specify
it in the `kubectl` command
- Try to make the database permissions easier to read and apply.
- Add a note about the different methods for authentication
- Add information about describing backup jobs
- Add info about running an ad-hoc backup job again by first deleting it.
- Add info about verifying AWS access
- Add info about name constraints for the cluster and node group names
This can save a lot of time as it otherwise fails late in the process if `_` is used.
- Change the expected time for cluster creating from 5 to 10 minutes to 5 to 20 …
=> zh: backup-to-s3, deploy-on-aws-eks: various small changes

en/TOC.md, en/releases/release-1.2.0-rc.1.md, zh/TOC.md, zh/releases/release-1.2.0-rc.1.md
add release notes for v1.2.0-rc.1
=> en, zh: add release notes for v1.2.0-rc.1

en/deploy-tidb-cluster-across-multiple-kubernetes.md, zh/access-dashboard.md, zh/deploy-on-aws-eks.md
- Add more details about accessing TiDB with an nlb with internal scheme
- Link to info about using TiDB Dashboard
- Update info about TiDB Dashboard with Kubernetes
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1212
pingcap/tidb-operator#3974
pingcap/tidb-operator#3941
=> zh: update info on EKS and dashboard access

en/deploy-tidb-dm.md, en/enable-tls-for-dm.md
update docs about data mount path for DM-worker
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1218
=> en: update docs about data mount path for DM-worker

en/deploy-tidb-dm.md, zh/deploy-tidb-dm.md
=> zh,en: add deploy DM min operator version note

zh/backup-restore-overview.md, zh/configure-a-tidb-cluster.md
add tikv level 2 parameter
add typical tikv lever 2 parameter
=> zh: Update configure-a-tidb-cluster.md

en/configure-a-tidb-cluster.md, zh/configure-a-tidb-cluster.md
=> zh,en: fix spelling mistake

en/cheat-sheet.md, en/deploy-tidb-binlog.md, en/destroy-a-tidb-cluster.md, en/restore-data-using-tidb-lightning.md, en/restore-from-gcs.md, en/restore-from-s3.md, en/tidb-toolkit.md
Improve the doc of tidb-lightning about restoring data 
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1217
=> en: improve the doc of tidb-lightning

en/configure-a-tidb-cluster.md
Add two parameters at the tikv level 
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1224
=> en: Update configure-a-tidb-cluster.md

en/tidb-operator-overview.md, zh/tidb-operator-overview.md
=> en, zh: remote the note for single operator

en/deploy-tidb-operator.md, zh/deploy-tidb-operator.md
=> zh, en: update command of tidb-operator upgrade

en/deploy-on-aws-eks.md, en/logs-collection.md, zh/deploy-on-aws-eks.md, zh/logs-collection.md
Update the docs to fix two broken links
=> en, zh: Update the docs to fix two broken links

en/_index.md, zh/_index.md
Update the compatible TiDB versions for  TiDB Operator because TiDB Operator should support all new TiDB releases
=> en, zh: Update the compatible TiDB versions for  TiDB Operator

en/monitor-a-tidb-cluster.md, zh/monitor-a-tidb-cluster.md
=> en, zh: Update the doc of setting kube-prometheus and AlertManager

en/deploy-tidb-operator.md, zh/deploy-tidb-operator.md
Add the section "Custom Operator" in [deploy-tidb-operator.md](https://github.com/pingcap/docs-tidb-operator/blob/master/zh/deploy-tidb-operator.md).
=> zh: add the section "Custom Operator"

en/configure-a-tidb-cluster.md, zh/configure-a-tidb-cluster.md
Add warning about `spec.tikv.evictLeaderTimeout` field.
https://github.com/tikv/tikv/pull/10364
=> en,zh: Add warning about `spec.tikv.evictLeaderTimeout` field

en/initialize-a-cluster.md, zh/initialize-a-cluster.md
file: [initialize-a-cluster.md](https://github.com/pingcap/docs-tidb-operator/blob/master/zh/initialize-a-cluster.md)
prompt the user to modify some required fields.
=> en, zh: update doc about deploying initializer

en/cheat-sheet.md, en/configure-storage-class.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/configure-storage-class.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-on-aws-eks.md, zh/deploy-on-gcp-gke.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
Bump Operator to v1.1.13
ref #1162
Run commands:
```shell
find . -type f | xargs sed -i "s/v1.1.12/v1.1.13/g"
```
=> en, zh: Bump Operator to v1.1.13

en/cheat-sheet.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
Bump Operator to v1.2.0-rc.2
ref #1239
Run commands:
```shell
find . -type f | xargs sed -i "s/v1.2.0-rc.1/v1.2.0-rc.2/g"
```
=> en, zh: Bump Operator to v1.2.0-rc.2

en/deploy-tidb-dm.md, en/enable-tls-for-dm.md, zh/deploy-tidb-dm.md, zh/enable-tls-for-dm.md
en,zh; Bump DM to v2.0.4
ref #1229
Run commands:
```shell
find . -type f | xargs sed -i "s/v2.0.3/v2.0.4/g"
```
=> en,zh; Bump DM to v2.0.4

en/backup-restore-overview.md, zh/backup-restore-overview.md
Close #1282
https://github.com/pingcap/tidb-operator/pull/4048
=> en, zh: Update description about `toolImage` field of BR

en/TOC.md, en/releases/release-1.2.0-rc.2.md, zh/TOC.md, zh/releases/release-1.2.0-rc.2.md
add release notes for v1.2.0-rc.2
=> en, zh: add release notes for v1.2.0-rc.2

en/enable-tls-between-components.md, en/enable-tls-for-dm.md, en/enable-tls-for-mysql-client.md, zh/enable-tls-between-components.md, zh/enable-tls-for-dm.md, zh/enable-tls-for-mysql-client.md
Close #1259
Prompt user not to modify names of Secret objects.
=> en, zh: prompt user not to modify names of Secret objects.

en/monitor-a-tidb-cluster.md, zh/aggregate-multiple-cluster-monitor-data.md
change aggregate-multiple-cluster-monitor-data.md
- [*] master (the latest development version)
- This PR is translated from: #1069
=> zh: update Thanos

en/_index.md, zh/_index.md
Remove two controlled characters from the index pages
=> en, zh: remove two controlled characters from the index pages

en/configure-a-tidb-cluster.md, zh/configure-a-tidb-cluster.md
=> en, zh: update the doc of configuring tidb cluster

zh/TOC.md, zh/enable_tls_for_ticdc.md, zh/enable_tls_for_ticdc_sink.md
=> zh: Add doc enable_tls_for_ticdc.md

en/configure-a-tidb-cluster.md, zh/configure-a-tidb-cluster.md
=> zh, en: update doc for tidb cluster config

zh/enable-tls-for-mysql-client.md
=> fix a typo

zh/configure-a-tidb-cluster.md, zh/use-auto-failover.md
=> zh: update the failover doc

en/aggregate-multiple-cluster-monitor-data.md
change aggregate-multiple-cluster-monitor-data.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1215
=> en: update Thanos

.github/pull_request_template.md
=> Add v1.2 in pull_request_template.md

zh/TOC.md, zh/whats-new-in-v1.2.md
=> zh: add what's new in v1.2

en/monitor-a-tidb-cluster.md, zh/monitor-a-tidb-cluster.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1254
=> en: Add monitor multiplecluster and thanos doc

en/cheat-sheet.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/monitor-a-tidb-cluster.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
Bump Operator to v1.2.0-rc.2
ref #1297
Run commands:
```shell
find . -type f | xargs sed -i "s/v1.2.0-rc.2/v1.2.0/g"
```
=> en, zh: Bump Operator to v1.2.0

en/TOC.md, en/whats-new-in-v1.2.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1329
=> en: add what's new in v1.2 

.circleci/config.yml, .github/workflows/ci.yaml, .github/workflows/dispatch.yml
=> Update the CI configs for release-1.2

en/tidb-operator-overview.md, zh/tidb-operator-overview.md
- [x master (the latest development version)
=> en, zh: Update TiDB Operator version on the overview page

hack/verify-link-anchors.sh
=> chore: lock lint plugin versions

crowdin.yml, en/canary-upgrade-tidb-operator.md, en/deploy-multiple-tidb-operator.md, zh/canary-upgrade-tidb-operator.md, zh/deploy-multiple-tidb-operator.md
=> en, zh: update docs for canary upgrade

en/deploy-tidb-dm.md, en/enable-tls-for-dm.md, zh/deploy-tidb-dm.md, zh/enable-tls-for-dm.md
en,zh; Bump DM to v2.0.4
ref #1294
Run commands:
```shell
find . -type f | xargs sed -i "s/v2.0.4/v2.0.6/g"
```
=> en,zh; Bump DM to v2.0.6

en/TOC.md, en/releases/release-1.2.1.md, zh/TOC.md, zh/releases/release-1.2.1.md
=> en, zh: add release notes for v1.2.1

en/configure-a-tidb-cluster.md, en/use-auto-failover.md
update the failover doc
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1311
=> en: update the failover doc

en/TOC.md, en/releases/release-1.2.2.md, zh/TOC.md, zh/releases/release-1.2.2.md
=> en,zh: add release notes for v1.2.2

en/TOC.md, en/releases/release-1.2.3.md, zh/TOC.md, zh/releases/release-1.2.3.md
=> en,zh: add release notes for v1.2.3

zh/TOC.md
fix link of v1.2.3 release note
=> fix link of v1.2.3 release note

en/_index.md, en/tidb-operator-overview.md, zh/_index.md, zh/tidb-operator-overview.md
=> en, zh: update support releases

.github/workflows/ci.yaml
Fix an error that `check-tags.py` never actually worked. (For details, see https://github.com/CharLotteiu/pingcap-docs-checks/issues/5)
The error is found in blog, docs-tidb-operator, and docs-dm.
=> .github: fix github action config

en/monitor-a-tidb-cluster.md, zh/monitor-a-tidb-cluster.md
Fix broken link and modify description about TiDBMonitor
=> en,zh: Fix broken link and modify description about TiDBMonitor

en/tidb-toolkit.md, zh/tidb-toolkit.md
Update the tikv-ctl local mode:
- Use `./tikv-ctl` as `tikv-ctl` is not in the `$PATH`
- Use `--data-dir` instead of `--db` (see also
https://github.com/tikv/website/issues/306 )
```
/ # tikv-ctl --db /var/lib/tikv/db size -r 2
sh: tikv-ctl: not found
/ # ./tikv-ctl --db /var/lib/tikv/db size -r 2
error: Invalid value for '--db <db>': DEPRECATED!!! Use --data-dir and --config instead
/ # ./tikv-ctl --data-dir /var/lib/tikv size -r 2
[2021/11/05 15:40:04.196 +00:00] [INFO] [mod.rs:118] ["encryption: none of key dictionary and file dictionary are found."]
[2021/11/05 15:40:04.196 +00:00] [INFO] [mod.rs:479] ["encryption is disabled."]
[2021/11/05 15:40:04.196 +00:00] [WARN] [config.rs:587] ["compaction guard is disabled due to region info provider not available"]
[2021/11/05 15:40:04.196 …
```
=> en, zh: tidb-toolkit: Fix tikv-ctl local mode

en/_index.md
=> Fix typo in the index

en/enable-tls-for-mysql-client.md
=> fix typo in /en/enable-tls-for-mysql-client.md

en/TOC.md, en/deploy-tidb-dm.md, en/enable-tls-for-dm.md, en/use-tidb-dm.md, zh/TOC.md, zh/deploy-tidb-dm.md, zh/enable-tls-for-dm.md, zh/use-tidb-dm.md
This PR is to resolve comments from https://asktug.com/t/topic/212852.
=> en, zh: split the instructions of DM deployment and usage

scripts/merge_by_toc.py
Since the structure of `TOC.md` has been changed, the parse method for generating PDF is failed. This PR is to fix the parse method.
And this issue caused by https://github.com/pingcap/docs-tidb-operator/pull/1441
=> update TOC.md parse method since TOC.md structure has been changed

en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md
=> en,zh; Use version-specific url

zh/configure-a-tidb-cluster.md, zh/deploy-tiflash.md
=> fix typos 'reqeust'

zh/aggregate-multiple-cluster-monitor-data.md
add tibdmonitor remote write introduction
=> zh:add tibdmonitor remote write introduction

en/TOC.md, en/deploy-cluster-on-arm64.md, en/deploy-on-alibaba-cloud.md, en/deploy-on-aws-eks.md, en/deploy-on-gcp-gke.md, en/deploy-on-general-kubernetes.md, en/get-started.md
Added a new document and notes about deploying a cluster on ARM64.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1301
=> en: add a doc and notes about deploying a cluster on ARM64

.gitignore, en/TOC.md, en/enable-dynamic-configuration-for-tidbmonitor.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1414
=> en: add tidbmonitor dynamic configuration

en/deploy-on-aws-eks.md, zh/deploy-on-aws-eks.md
Add aws instance type recommendation.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1427
=> en: add aws instance type recommendation

en/TOC.md, zh/TOC.md
Optimize the organization of TOC topics
=> en, zh: reorganize TOC topics

en/restart-a-tidb-cluster.md, zh/restart-a-tidb-cluster.md
fix https://github.com/pingcap/docs-tidb-operator/issues/1483
https://github.com/pingcap/tidb-operator/pull/4279
=> en,zh: graceful restart tikv

en/configure-a-tidb-cluster.md, zh/configure-a-tidb-cluster.md
changed github.com/pingcap/ticdc to github.com/pingcap/tiflow
changed github.com/pingcap/ticdc to github.com/pingcap/tiflow
=> changed github.com/pingcap/ticdc to github.com/pingcap/tiflow

en/aggregate-multiple-cluster-monitor-data.md
Add tidbmonitor remote write
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1399
=> en: add tidbmonitor remote write

en/TOC.md, en/enable-monitor-dynamic-configuration.md
The filename was not aligned in the previous PR https://github.com/pingcap/docs-tidb-operator/pull/1463
=> en: rename tidbmonitor dynamic config to align with zh

en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/upgrade-tidb-operator.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/upgrade-tidb-operator.md
Merge after PR https://github.com/pingcap/tidb-operator/pull/4151
Fix https://github.com/pingcap/docs-tidb-operator/issues/1464
=> en,zh: Adjust for v1 CRD

en/deploy-on-aws-eks.md, zh/deploy-on-aws-eks.md
add ebs-csi-node toleration
- [*] master (the latest development version)
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/issues/1479
- [*] Change aliases
fix #1479
=> en, zh: add ebs-csi-node toleration

en/enable-monitor-dynamic-configuration.md
=> en: fix aliases in monitor dynamic config

en/get-started.md, zh/get-started.md
=> deleted font tags

en/get-started.md, zh/get-started.md
=> fix <pre><code> tags

zh/get-started.md
corrected a typo in get-started
=> corrected a typo in get-started

en/deploy-on-aws-eks.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1476
=> en: update eks storagclass config

en/TOC.md, en/deploy-multiple-tidb-operator.md, zh/TOC.md, zh/deploy-multiple-tidb-operator.md
Optimize deploy multiple operator
=> Optimize deploy multiple operator

en/get-started.md, zh/get-started.md
=> Fix links and code block format

en/cheat-sheet.md, en/deploy-cluster-on-arm64.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/deploy-cluster-on-arm64.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
Bump Operator to v1.2.5
ref #1418
Run commands and some manual fix:
```shell
find . -type f | xargs sed -i "s/v1.2.4/v1.2.5/g"
```
=> en,zh: Bump operator to v1.2.5

zh/TOC.md, zh/pd-recover.md, zh/recover-deleted-cluster.md
Optimizer disaster recovery docs
=> Optimizer disaster recovery docs

zh/get-started.md
=> Add a stop

en/get-started.md, zh/get-started.md
=> Polished format in details

en/get-started.md, zh/get-started.md
Updated descriptions about minikube
=> Updated descriptions about minikube

zh/get-started.md
=> update get-started doc

en/get-started.md, zh/get-started.md
- This PR is translated from: (https://github.com/pingcap/docs-tidb-operator/pull/1553)
=> Verified the doc and made changes

en/enable-tidb-cluster-auto-scaling.md, en/scale-a-tidb-cluster.md, zh/enable-tidb-cluster-auto-scaling.md, zh/scale-a-tidb-cluster.md
- Update titles of two scaling files
- Improve the content
=> en, zh: improve scaling documents

en/containers-run-as-non-root-user.md, en/deploy-ticdc.md, en/enable-tls-for-ticdc-sink.md, zh/containers-run-as-non-root-user.md, zh/deploy-ticdc.md, zh/enable-tls-for-ticdc-sink.md
- Improve documents related to security
- Update outdated TiCDC links
=> en, zh: improve security documents

en/tidb-operator-overview.md, zh/tidb-operator-overview.md
Add Azure deployment doc to overview.md
=> en, zh: add azure in overview

en/TOC.md, en/releases/release-1.2.6.md, zh/TOC.md, zh/releases/release-1.2.6.md
=> en,zh: add release notes for v1.2.6

zh/maintain-a-kubernetes-node.md
update migrate TiKV Pod
Fix #1400
=> zh: update migrate TiKV Pod

en/backup-restore-overview.md, en/cheat-sheet.md, en/deploy-on-alibaba-cloud.md, en/deploy-on-aws-eks.md, en/deploy-on-azure-aks.md, en/deploy-on-gcp-gke.md, en/deploy-tidb-binlog.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tiflash.md, en/enable-tls-between-components.md, en/grant-permissions-to-remote-storage.md, en/pause-sync-of-tidb-cluster.md, en/pd-recover.md, en/scale-a-tidb-cluster.md, en/use-auto-failover.md, zh/backup-restore-overview.md, zh/cheat-sheet.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-on-aws-eks.md, zh/deploy-on-azure-aks.md, zh/deploy-on-gcp-gke.md, zh/deploy-tidb-binlog.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tiflash.md, zh/enable-tls-between-components.md, zh/grant-permissions-to-remote-storage.md, zh/pause-sync-of-tidb-cluster.md, zh/pd-recover.md, zh/scale-a-tidb-cluster.md, zh/use-auto-failover.md
replace `kubectl edit` to `kubectl patch`
Fix #1048
=> zh,en;replace `kubectl edit` to `kubectl patch`

zh/access-dashboard.md
- Other reference link(s): https://github.com/pingcap/docs-tidb-operator/pull/1581
=> zh: fix the description about continue profile

en/deploy-tidb-dm.md, zh/deploy-tidb-dm.md
=> update dm deploy

en/get-started.md
Fix https://github.com/pingcap/docs-tidb-operator/issues/1509
- Removed Note section
- Update startup message using minikube v1.24.0
- Other reference link(s): https://github.com/pingcap/docs-tidb-operator/issues/1509
=> minikube default installation using Docker can be used for TiDB

en/cheat-sheet.md, en/deploy-cluster-on-arm64.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/deploy-cluster-on-arm64.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
=> en,zh: Bump Operator version to v1.3.0-beta.1

zh/releases/release-1.3.0-beta.1.md
=> zh: use internal link

zh/access-dashboard.md
=> zh: Fix ngm example

zh/replace-nodes-for-local-disk.md
=> zh: remove extra spaces

en/logs-collection.md, zh/logs-collection.md
Fix https://github.com/pingcap/docs-tidb-operator/issues/1601
=> en,zh: fix broken links caused by logstash

en/access-dashboard.md
Add description about continue profile
- This PR is translated from:  https://github.com/pingcap/docs-tidb-operator/pull/1581, https://github.com/pingcap/docs-tidb-operator/pull/1585, https://github.com/pingcap/docs-tidb-operator/pull/1595
=> en: Add description about continue profile

zh/use-auto-failover.md
=> zh: update auto failover recover

en/upgrade-tidb-operator.md, zh/upgrade-tidb-operator.md
Close https://github.com/pingcap/tidb-operator/issues/4275
=> en,zh: add note for upgrade cmd after v1.3.0

en/releases/release-1.3.0-beta.1.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1591
=> en: add continous profiling link to release notes

en/deploy-failures.md, zh/deploy-failures.md
=> en, zh: Add pd nslookup issue

.github/pull_request_template.md
=> .github: add v1.3 to pr template

en/maintain-a-kubernetes-node.md, zh/maintain-a-kubernetes-node.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1403
=> en: add doc for migrate pd/tikv pod

en/deploy-tidb-binlog.md, zh/deploy-tidb-binlog.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1572
=> en: update scale tidb-binlog

en/maintain-a-kubernetes-node.md
Update steps for migrating TiKV Pod.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1521
=> en: update steps for migrating TiKV Pod

en/use-auto-failover.md
update doc for auto failover
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1594
=> en: update doc for auto failover

zh/get-started.md
Update get-started to use docker as the default minikube installation method.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1544
=> zh: update minikube default installation using docker

en/configure-a-tidb-cluster.md, zh/configure-a-tidb-cluster.md
=> en,zh: optimize docs for TiKV upgrade configuration

en/upgrade-tidb-operator.md, zh/upgrade-tidb-operator.md
en,zh: Revert some change about upgrade
=> en,zh: Revert some change about upgrade

en/TOC.md, en/enable-monitor-shards.md
Add a doc for enabling TidbMonitor shards.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1415
=> en: add doc for tidbmonitor shards

en/releases/release-1.3.0-beta.1.md, zh/releases/release-1.3.0-beta.1.md
add rolling update changes missed in v1.3.0-beta.1
=> en,zh; add rolling update changes missed in v1.3.0-beta.1

en/_index.md, en/tidb-operator-overview.md, zh/_index.md, zh/tidb-operator-overview.md
=> update support versions

en/deploy-on-aws-eks.md, zh/deploy-on-aws-eks.md
=> Add Amazon Linux 2 AMI recommendation.

en/releases/release-1.3.0-beta.1.md, en/whats-new-in-v1.3.md, zh/releases/release-1.3.0-beta.1.md, zh/whats-new-in-v1.3.md
=> en,zh: add missed change to v1.3.0-beta.1 change log

en/cheat-sheet.md, en/deploy-cluster-on-arm64.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/deploy-cluster-on-arm64.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
ref #1576 
Run Commands:
```sh
find . -type f | xargs sed -i "s/v1.2.6/v1.2.7/g"
```
=> en,zh; bump operator version to v1.2.7

en/TOC.md, en/releases/release-1.2.7.md, zh/TOC.md, zh/releases/release-1.2.7.md
=> en,zh; Add release notes for v1.2.7

en/cheat-sheet.md, en/configure-storage-class.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/configure-storage-class.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-on-aws-eks.md, zh/deploy-on-gcp-gke.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
Bump Operator to v1.1.15
ref #1419 
Run commands:
```shell
find . -type f | xargs sed -i "s/v1.1.14/v1.1.15/g"
```
=> en,zh; bump operator version to v1.1.15

en/TOC.md, en/releases/release-1.1.15.md, zh/TOC.md, zh/releases/release-1.1.15.md
=> en,zh; add release notes for v1.1.15

en/releases/release-1.3.0-beta.1.md, en/whats-new-in-v1.3.md, zh/releases/release-1.3.0-beta.1.md, zh/whats-new-in-v1.3.md
=> en,zh: optimize changelog about 1.3.0

en/build-multi-aws-eks.md, en/build-multi-gcp-gke.md, en/deploy-tidb-cluster-across-multiple-kubernetes.md, zh/build-multi-aws-eks.md, zh/build-multi-gcp-gke.md, zh/deploy-tidb-cluster-across-multiple-kubernetes.md
=> en,zh: optmize doc about deploy tidb cluster across kubernetes

en/_index.md, en/tidb-operator-overview.md, zh/_index.md, zh/tidb-operator-overview.md
=> en,zh: update tidb & operator version choice

en/backup-restore-overview.md, zh/backup-restore-cr.md
=> en,zh: add s3 fields description for br doc

en/deploy-on-gcp-gke.md, zh/deploy-on-gcp-gke.md
=> en,zh: add GKE instance type recommendation 

en/deploy-tidb-operator.md, zh/deploy-tidb-operator.md
=> add redirects for deploy-tidb-operator.md

en/deploy-tidb-operator.md, zh/deploy-tidb-operator.md
Move redirects to 1.3 (https://github.com/pingcap/docs-tidb-operator/pull/1715)
=> remove redirects

en/backup-to-aws-s3-using-br.md, en/backup-to-gcs-using-br.md, en/backup-to-gcs.md, en/backup-to-pv-using-br.md, en/restore-from-aws-s3-using-br.md, en/restore-from-gcs-using-br.md, en/restore-from-gcs.md, en/restore-from-pv-using-br.md, en/restore-from-s3.md, zh/backup-to-aws-s3-using-br.md, zh/backup-to-gcs-using-br.md, zh/backup-to-gcs.md, zh/backup-to-pv-using-br.md, zh/restore-from-aws-s3-using-br.md, zh/restore-from-gcs-using-br.md, zh/restore-from-gcs.md, zh/restore-from-pv-using-br.md, zh/restore-from-s3.md
As suggested in https://github.com/pingcap/docs-tidb-operator/pull/1709#discussion_r816701145
=> en,zh: use 1.2.7 rbac link for v1.2 docs

zh/configure-a-tidb-cluster.md
Close #1139 
Close https://github.com/pingcap/docs/issues/5069
=> zh: add more config description

en/deploy-tidb-cluster-across-multiple-kubernetes.md, zh/deploy-tidb-cluster-across-multiple-kubernetes.md
=> en,zh: add descrption about cluster domain

zh/configure-a-tidb-cluster.md, zh/faq.md
=> zh: add FAQ about configUpdateStrategy

en/restore-from-pv-using-br.md, zh/restore-from-pv-using-br.md
=> Correct path in doc about NFS restore

en/aggregate-multiple-cluster-monitor-data.md, en/deploy-cluster-on-arm64.md, en/deploy-heterogeneous-tidb-cluster.md, en/enable-monitor-dynamic-configuration.md, en/enable-monitor-shards.md, en/enable-tls-between-components.md, en/monitor-a-tidb-cluster.md, zh/aggregate-multiple-cluster-monitor-data.md, zh/deploy-cluster-on-arm64.md, zh/deploy-heterogeneous-tidb-cluster.md, zh/enable-monitor-dynamic-configuration.md, zh/enable-monitor-shards.md, zh/enable-tls-between-components.md, zh/monitor-a-tidb-cluster.md
close #1368 
1. adding prometheusReloader to all examples in docs
2. refine docs for using customized configurations
=> feat(monitor): update docs

en/configure-a-tidb-cluster.md, en/deploy-ticdc.md, zh/configure-a-tidb-cluster.md, zh/deploy-ticdc.md
close #1717 
add volume mount docs for ticdc
=> add volume mount docs for ticdc

en/maintain-a-kubernetes-node.md, zh/maintain-a-kubernetes-node.md
=> en,zh: add doc about recreate TiKV Pod

en/configure-storage-class.md, zh/configure-storage-class.md
Close #1253
Ref [#4428](https://github.com/pingcap/tidb-operator/pull/4428)
=> en,zh: optimize doc about local pv

en/backup-to-aws-s3-using-br.md, en/backup-to-gcs-using-br.md, en/backup-to-pv-using-br.md, zh/backup-to-aws-s3-using-br.md, zh/backup-to-gcs-using-br.md, zh/backup-to-pv-using-br.md
Original PR: https://github.com/pingcap/docs-tidb-operator/pull/1622
closing #1622 because CLA didn't work. 
=> en,zh: add backup examples to backup using br docs

en/canary-upgrade-tidb-operator.md, en/upgrade-tidb-operator.md
Update en doc for canary upgrade. 
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1508
=> en: update doc for canary upgrade

zh/backup-restore-cr.md
=> add all fields in crd to br docs

en/TOC.md, en/releases/release-1.3.1.md, en/releases/release-1.3.2.md, zh/TOC.md, zh/releases/release-1.3.1.md, zh/releases/release-1.3.2.md
=> en,zh: add release notes for v1.3.2

en/cheat-sheet.md, en/deploy-cluster-on-arm64.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/deploy-cluster-on-arm64.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
=> en,zh: bump operator version to v1.3.2

en/configure-a-tidb-cluster.md, en/deploy-on-alibaba-cloud.md, en/deploy-on-aws-eks.md, en/deploy-on-azure-aks.md, en/deploy-on-gcp-gke.md, en/deploy-ticdc.md, en/deploy-tidb-binlog.md, en/deploy-tiflash.md, en/upgrade-a-tidb-cluster.md, zh/configure-a-tidb-cluster.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-on-aws-eks.md, zh/deploy-on-azure-aks.md, zh/deploy-on-gcp-gke.md, zh/deploy-ticdc.md, zh/deploy-tidb-binlog.md, zh/deploy-tiflash.md, zh/upgrade-a-tidb-cluster.md
delete "enterprise" content from docs
=> en, zh: delete "enterprise" content from docs

.github/workflows/ci.yaml
=> ci: update ci path

en/monitor-kubernetes.md, zh/monitor-kubernetes.md
closes https://github.com/pingcap/docs-tidb-operator/issues/1820 https://github.com/pingcap/docs-tidb-operator/issues/1814
=> fix 2 broken links

en/TOC.md, en/releases/release-1.3.3.md, zh/TOC.md, zh/releases/release-1.3.3.md
=> en,zh: add release note 1.3.3

en/cheat-sheet.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
=> en,zh: Bump operator version to v1.3.3

en/configure-a-tidb-cluster.md, en/faq.md, zh/configure-a-tidb-cluster.md
- Add a faq about configratuion update stragety.
- Add description for `configUpdateStrategy: RollingUpdate`.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1718
=> en: add faq about configUpdateStrategy

en/enable-tls-between-components.md, en/enable-tls-for-dm.md, en/enable-tls-for-mysql-client.md, zh/enable-tls-for-mysql-client.md
Add config description for TLS clusters.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1757
=> en: improve TLS docs

zh/TOC.md
Add Technical Preview for PingCAP Clinic.
=> Add Technical Preview for PingCAP Clinic

.github/exclude-links.txt
Close https://github.com/pingcap/docs-tidb-operator/issues/1838
=> Add exclude-links

en/backup-restore-cr.md, zh/backup-restore-cr.md
Add missing fields to backup restore CR.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1738
=> en: add fields in br crd

en/get-started.md, zh/get-started.md
Add aliases for the two docs deleted in https://github.com/pingcap/docs-tidb-operator/pull/1847
=> add aliases for kind doc in v1.0

.github/workflows/ci.yaml
=> ci: update node-version to 16

.github/workflows/ci.yaml
Fix the Node.js version in all jobs. :face_with_head_bandage: 
=> ci: update node version (again)

en/pd-recover.md, zh/pd-recover.md
Close https://github.com/pingcap/docs-tidb-operator/issues/1865
=> fix quote missed error

en/releases/release-1.2.7.md, en/releases/release-1.3.0.md, zh/releases/release-1.2.7.md, zh/releases/release-1.3.0.md
=> en, zh: fix a typo in release notes

en/TOC.md, en/releases/release-1.3.4.md, zh/TOC.md, zh/releases/release-1.3.4.md
=> en,zh: release note for 1.3.4

en/cheat-sheet.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
Bump Operator to v1.3.4
```shell
find . -type f | xargs sed -i "s/v1.3.3/v1.3.4/g"
```
=> en,zh: Bump operator to v1.3.4

en/backup-to-s3.md
Close https://github.com/pingcap/docs-tidb-operator/issues/1879
`https://docs.pingcap.com/tidb/dev/export-or-backup-using-dumpling` -> 400
=> Dumpling: fix broken link

zh/backup-restore-cr.md, zh/backup-to-azblob-using-br.md, zh/grant-permissions-to-remote-storage.md, zh/restore-from-azblob-using-br.md
Closes #1892
Added - Support BR on Azure Blob Storage
- Other reference link(s):  https://github.com/pingcap/tidb-operator/pull/4534
=> zh: Support BR on Azure Blob Storage

en/TOC.md, en/backup-restore-cr.md, en/backup-restore-overview.md, en/backup-to-aws-s3-using-br.md, en/backup-to-azblob-using-br.md, en/backup-to-gcs-using-br.md, en/grant-permissions-to-remote-storage.md, en/restore-from-azblob-using-br.md, zh/TOC.md, zh/backup-restore-overview.md, zh/backup-to-aws-s3-using-br.md, zh/backup-to-azblob-using-br.md, zh/backup-to-gcs-using-br.md, zh/grant-permissions-to-remote-storage.md
Signed-off-by: Ran <huangran.alex@gmail.com>
add docs for backup data to azblob
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1894
=> en: add doc for backup data to azblob

en/TOC.md, en/releases/release-1.3.6.md, zh/TOC.md, zh/releases/release-1.3.6.md
=> en,zh: release note for 1.3.6

en/backup-restore-overview.md, en/backup-to-aws-s3-using-br.md, en/backup-to-azblob-using-br.md, en/backup-to-gcs-using-br.md, en/backup-to-pv-using-br.md, en/restore-from-aws-s3-using-br.md, en/restore-from-azblob-using-br.md, en/restore-from-gcs-using-br.md, en/restore-from-pv-using-br.md
Close https://github.com/pingcap/docs-tidb-operator/issues/1925
- Other reference link(s):https://github.com/pingcap/docs/pull/8628
=> Fix broken link

en/backup-to-aws-s3-using-br.md, en/backup-to-azblob-using-br.md, en/backup-to-gcs-using-br.md, en/backup-to-pv-using-br.md
=> fix back-up-incremental-data link

en/TOC.md, en/clinic-data-collection.md, en/clinic-user-guide.md, zh/TOC.md, zh/clinic-data-collection.md, zh/clinic-user-guide.md
=> add content for clinic us

en/_index.md, en/clinic-user-guide.md, en/configure-a-tidb-cluster.md, en/deploy-heterogeneous-tidb-cluster.md, en/get-started.md, zh/_index.md, zh/clinic-user-guide.md, zh/configure-a-tidb-cluster.md, zh/deploy-heterogeneous-tidb-cluster.md, zh/deploy-tidb-monitor-across-multiple-kubernetes.md, zh/get-started.md, zh/tidb-operator-overview.md
=> fix simpletab issues

en/cheat-sheet.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
=> bump operator to v1.3.7

en/TOC.md, en/releases/release-1.3.7.md, zh/TOC.md, zh/releases/release-1.3.7.md
=> release note for 1.3.7

en/get-started.md
=> operator: updated video link

.github/workflows/prevent-deletion.yaml
=> CI: fix prevent-deletion

en/TOC.md, en/releases/release-1.3.8.md, zh/TOC.md, zh/releases/release-1.3.8.md
=> en,zh: release notes for 1.3.8

en/cheat-sheet.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
```shell
find . -type f | xargs sed -i "s/v1.3.7/v1.3.8/g"
```
=> bump operator to v1.3.8

en/configure-a-tidb-cluster.md, en/deploy-failures.md, en/deploy-ticdc.md, en/deploy-tidb-binlog.md, en/enable-tls-for-mysql-client.md, en/faq.md, en/monitor-a-tidb-cluster.md, en/pd-recover.md, en/tidb-toolkit.md
closes https://github.com/pingcap/docs-tidb-operator/issues/1994
=> Fix broken links

en/TOC.md, en/deploy-tidb-cluster-across-multiple-kubernetes.md, en/deploy-tidb-monitor-across-multiple-kubernetes.md, zh/deploy-tidb-monitor-across-multiple-kubernetes.md
Add docs about multi cluster prom monitoring.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/1490
=> en: add doc for multi-cluster prometheus monitor

en/configure-a-tidb-cluster.md, zh/configure-a-tidb-cluster.md
=> set labels for tidb

en/deploy-heterogeneous-tidb-cluster.md, en/deploy-on-azure-aks.md, en/deploy-tiflash.md, zh/deploy-heterogeneous-tidb-cluster.md, zh/deploy-tiflash.md
- Other reference link(s): https://github.com/pingcap/docs/pull/10557, https://github.com/pingcap/docs-cn/pull/11428
=> Fix admonition format

en/deploy-on-aws-eks.md, en/deploy-on-gcp-gke.md, zh/deploy-on-aws-eks.md, zh/deploy-on-gcp-gke.md
=> en, zh: Update recommended instance type

zh/releases/release-1.3.8.md
fix link in release-1.3.8 zh, see link in en is correct.
=> fix-release-1.3.8-zh

en/backup-and-restore-using-helm-charts.md, en/configure-backup.md, en/notes-tidb-operator-v1.1.md, en/tidb-cluster-chart-config.md, zh/backup-and-restore-using-helm-charts.md, zh/configure-backup.md, zh/notes-tidb-operator-v1.1.md, zh/tidb-cluster-chart-config.md
Signed-off-by: Ran <huangran.alex@gmail.com>
=> add aliases for 8 docs

en/TOC.md, en/releases/release-1.3.9.md, zh/TOC.md, zh/releases/release-1.3.9.md
=> en,zh: release note for 1.3.9

en/cheat-sheet.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
```shell
find . -type f | xargs sed -i "s/v1.3.8/v1.3.9/g"
```
=> en,zh: bump operator to v1.3.9

en/restore-from-aws-s3-using-br.md, zh/restore-from-aws-s3-using-br.md
=> fix-spelling in restore-from-aws-s3-using-br

en/configure-storage-class.md, zh/configure-storage-class.md
lack one '}' so this command will retrun `Error from server (BadRequest): unexpected EOF`
=> fix-configure-storage-class

en/advanced-statefulset.md, zh/advanced-statefulset.md
=> Add a step to check asts is deployed

en/TOC.md, en/releases/release-1.4.0-beta.1.md, zh/TOC.md, zh/releases/release-1.4.0-beta.1.md
=> en,zh: add 1.4.0-beta.1 release notes

en/faq.md, en/modify-tidb-configuration.md, en/prerequisites.md, zh/backup-to-gcs.md, zh/backup-to-s3.md, zh/benchmark-sysbench.md, zh/modify-tidb-configuration.md, zh/restore-from-azblob-using-br.md, zh/restore-from-gcs-using-br.md
=> en,zh: update old links

zh/backup-to-azblob-using-br.md, zh/restore-from-azblob-using-br.md
Signed-off-by: Leavrth <jianjun.liao@outlook.com>
=> zh: fix typos of config

en/pd-recover.md, zh/pd-recover.md
customer missed `delete pvc` step and get error when excute `pd-recover`
Customer is confused because he confirmed PD Pod is started, actually PD process is not started. This PR will change confirm step to ensure PD process is started.
=> improve pd recover doc

en/_index.md, zh/_index.md
Changed the home page to learning path style
=> *: changed to learning path style

en/TOC.md, en/_index.md, zh/TOC.md, zh/_index.md
Fix links in learning path.
Add learning path in TOC.
=> fix links in learning path

en/backup-to-azblob-using-br.md, en/restore-from-azblob-using-br.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/2063
=> en: fix typos of config in backup and restore in azblob

en/TOC.md, en/releases/release-1.4.0-beta.2.md, zh/TOC.md, zh/releases/release-1.4.0-beta.2.md
=> en,zh: add 1.4.0-beta.2 release note

en/cheat-sheet.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
`find . -type f | xargs sed -i "s/v1.4.0-beta.1/v1.4.0-beta.2/g"`
=> bump v1.4.0-beta.1 to v1.4.0-beta.2

en/clinic-user-guide.md, zh/clinic-user-guide.md
=> update diag version to 1.2.1

en/TOC.md, en/cheat-sheet.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/releases/release-1.4.0-beta.3.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/TOC.md, zh/cheat-sheet.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/releases/release-1.4.0-beta.3.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
Signed-off-by: xhe <xw897002528@gmail.com>
=> bump v1.4.0-beta.2 to v1.4.0-beta.3

zh/access-dashboard.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-on-aws-eks.md, zh/deploy-on-azure-aks.md, zh/deploy-on-gcp-gke.md, zh/get-started.md, zh/whats-new-in-v1.3.md
- Code: https://github.com/pingcap/tidb-operator/pull/4787
=> [zh] Docs for seperated tidb-dashboard deployment

en/access-dashboard.md, en/deploy-on-alibaba-cloud.md, en/deploy-on-aws-eks.md, en/deploy-on-azure-aks.md, en/deploy-on-gcp-gke.md, en/get-started.md
- This PR is translated from:  https://github.com/pingcap/docs-tidb-operator/pull/2105
=> en: docs for separated tidb-dashboard deployment

en/deploy-on-azure-aks.md, zh/deploy-on-azure-aks.md
close issues [1850](https://github.com/pingcap/docs-tidb-operator/issues/1850)
=> fix note for lb in deploy-on-azure-aks.md

en/grant-permissions-to-remote-storage.md, zh/grant-permissions-to-remote-storage.md
Update backup requires permission for backup and restore
v1.4.0.beta.3
=> feat: update permission for ebs backup and restore

en/build-multi-gcp-gke.md
=> fix missing \ in create cluster command

en/TOC.md, en/backup-restore-faq.md, en/backup-restore-snapshot-perf.md, en/restore-from-aws-s3-by-snapshot.md
- This PR is translated from:  https://github.com/pingcap/docs-tidb-operator/pull/2108
=> en: snapshot-volume backup and restore

en/access-dashboard.md, zh/access-dashboard.md
=> Fix separate dashboard

en/upgrade-a-tidb-cluster.md, zh/upgrade-a-tidb-cluster.md
=> add-tiflash-in-upgrade-doc

en/advanced-statefulset.md, en/aggregate-multiple-cluster-monitor-data.md, en/backup-to-s3.md, en/cheat-sheet.md, en/configure-storage-class.md, en/deploy-on-alibaba-cloud.md, en/deploy-on-aws-eks.md, en/deploy-on-azure-aks.md, en/deploy-on-gcp-gke.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/advanced-statefulset.md, zh/aggregate-multiple-cluster-monitor-data.md, zh/backup-to-s3.md, zh/cheat-sheet.md, zh/configure-storage-class.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-on-aws-eks.md, zh/deploy-on-azure-aks.md, zh/deploy-on-gcp-gke.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
```shell
find . -type f | xargs sed -i "s/tidb-operator\/master/tidb-operator\/v1.4.0/g"
find . -type f | xargs sed -i "s/v1.4.0-beta.3/v1.4.0/g"
```
=> bump operator to v1.4.0 for release-1.4

en/cheat-sheet.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
=> en,zh: bump operator to v1.4.0

en/_index.md
Signed-off-by: Ran <huangran.alex@gmail.com>
=> trigger pdf on 1.3

en/upgrade-tidb-operator.md, zh/upgrade-tidb-operator.md
=> zh,en: update tidb-operator upgrade

en/advanced-statefulset.md, en/aggregate-multiple-cluster-monitor-data.md, en/backup-to-s3.md, en/configure-storage-class.md, en/deploy-on-aws-eks.md, en/deploy-on-azure-aks.md, en/deploy-on-gcp-gke.md, en/deploy-tidb-from-kubernetes-gke.md, en/enable-tidb-cluster-auto-scaling.md, en/get-started.md, zh/advanced-statefulset.md, zh/aggregate-multiple-cluster-monitor-data.md, zh/backup-to-s3.md, zh/configure-storage-class.md, zh/deploy-on-aws-eks.md, zh/deploy-on-azure-aks.md, zh/deploy-on-gcp-gke.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/enable-tidb-cluster-auto-scaling.md, zh/get-started.md
```shell
find . -type f | xargs sed -i "s/tidb-operator\/master/tidb-operator\/v1.2.7/g"
```
=> release-1.2: update CRD link to v1.2

en/aggregate-multiple-cluster-monitor-data.md, en/configure-storage-class.md, en/deploy-on-aws-eks.md, en/deploy-on-azure-aks.md, en/deploy-on-gcp-gke.md, en/deploy-tidb-from-kubernetes-gke.md, en/enable-tidb-cluster-auto-scaling.md, en/get-started.md, zh/aggregate-multiple-cluster-monitor-data.md, zh/configure-storage-class.md, zh/deploy-on-aws-eks.md, zh/deploy-on-azure-aks.md, zh/deploy-on-gcp-gke.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/enable-tidb-cluster-auto-scaling.md, zh/get-started.md
```shell
find . -type f | xargs sed -i "s/tidb-operator\/master/tidb-operator\/v1.3.9/g"
```
=> release-1.3: update CRD link to v1.3

en/advanced-statefulset.md, en/backup-to-s3.md, en/configure-storage-class.md, en/deploy-on-aws-eks.md, en/deploy-on-azure-aks.md, en/deploy-on-gcp-gke.md, en/deploy-tidb-from-kubernetes-gke.md, en/enable-tidb-cluster-auto-scaling.md, en/get-started.md, zh/advanced-statefulset.md, zh/backup-to-s3.md, zh/configure-storage-class.md, zh/deploy-on-aws-eks.md, zh/deploy-on-azure-aks.md, zh/deploy-on-gcp-gke.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/enable-tidb-cluster-auto-scaling.md, zh/get-started.md
```shell
find . -type f | xargs sed -i "s/tidb-operator\/master/tidb-operator\/v1.1.15/g"
```
=> release-1.1: update CRD link to v1.1

en/releases/release-1.4.0.md, zh/releases/release-1.4.0.md
=> zh,en: fix 1.4.0 release notes format

en/_index.md, zh/_index.md
Signed-off-by: Aolin <aolin.zhang@pingcap.com>
=> Bump version v1.4

en/restore-from-aws-s3-by-snapshot.md, zh/restore-from-aws-s3-by-snapshot.md
fix doc description, move backupType and restoreMode to `spec` from `br`
Close #2165 
=> fix: wrong crd fields under br in crd example

en/grant-permissions-to-remote-storage.md, en/restore-data-using-tidb-lightning.md, zh/grant-permissions-to-remote-storage.md, zh/restore-data-using-tidb-lightning.md
remove unnecessary `-n` in command which will cause command error, add necessary `${namespace}` after `-n` or command will also return error.
=> fix-annotate-command

en/backup-restore-snapshot-perf.md, en/grant-permissions-to-remote-storage.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/2169
=> en: refactor the volume-snapshot restore performance description

en/TOC.md, en/releases/release-1.4.1.md, zh/TOC.md, zh/releases/release-1.4.1.md
=> en,zh: add v1.4.1 release notes

en/cheat-sheet.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
```base
find . -type f | xargs sed -i "s/v1.4.0/v1.4.1/g" 
git checkout -- zh/whats-new-in-v1.4.md en/whats-new-in-v1.4.md 
```
and many manual revert
=> bump operator to v1.4.1 for master

en/advanced-statefulset.md, en/aggregate-multiple-cluster-monitor-data.md, en/backup-to-s3.md, en/cheat-sheet.md, en/configure-storage-class.md, en/deploy-on-alibaba-cloud.md, en/deploy-on-aws-eks.md, en/deploy-on-azure-aks.md, en/deploy-on-gcp-gke.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/advanced-statefulset.md, zh/aggregate-multiple-cluster-monitor-data.md, zh/backup-to-s3.md, zh/cheat-sheet.md, zh/configure-storage-class.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-on-aws-eks.md, zh/deploy-on-azure-aks.md, zh/deploy-on-gcp-gke.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
```base
find . -type f | xargs sed -i "s/v1.4.0/v1.4.1/g" 
git checkout -- zh/whats-new-in-v1.4.md en/whats-new-in-v1.4.md 
```
and many manual revert
=> bump operator to v1.4.1 for release-1.4

en/backup-to-aws-s3-using-br.md, en/backup-to-azblob-using-br.md, en/backup-to-gcs-using-br.md, en/restore-from-aws-s3-using-br.md, en/restore-from-azblob-using-br.md, en/restore-from-gcs-using-br.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/2146
=> en: add aws and gcp pitr docs

en/configure-a-tidb-cluster.md
=> en/configure-a-tidb-cluster.md: Fix formatting

en/cheat-sheet.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
```bash
find . -type f | xargs sed -i "s/v1.4.1/v1.4.2/g"
````
=> bump operator to v1.4.2

en/advanced-statefulset.md, en/aggregate-multiple-cluster-monitor-data.md, en/backup-to-s3.md, en/cheat-sheet.md, en/configure-storage-class.md, en/deploy-on-alibaba-cloud.md, en/deploy-on-aws-eks.md, en/deploy-on-azure-aks.md, en/deploy-on-gcp-gke.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/advanced-statefulset.md, zh/aggregate-multiple-cluster-monitor-data.md, zh/backup-to-s3.md, zh/cheat-sheet.md, zh/configure-storage-class.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-on-aws-eks.md, zh/deploy-on-azure-aks.md, zh/deploy-on-gcp-gke.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
```bash
find . -type f | xargs sed -i "s/v1.4.1/v1.4.2/g"
````
=> Bump operator to v1.4.2 for release 1.4 

en/TOC.md, en/releases/release-1.4.2.md, zh/TOC.md, zh/releases/release-1.4.2.md
=> en,zh: release note for 1.4.2

.github/workflows/media.yml, scripts/upload.py
stop uploading media and pdf to aws
=> chore: stop uploading media and pdf to aws

en/deploy-on-alibaba-cloud.md, en/deploy-on-aws-eks.md, en/deploy-on-azure-aks.md, en/deploy-on-gcp-gke.md, en/deploy-on-general-kubernetes.md, en/deploy-tidb-from-kubernetes-gke.md, en/upgrade-a-tidb-cluster.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-on-aws-eks.md, zh/deploy-on-azure-aks.md, zh/deploy-on-gcp-gke.md, zh/deploy-on-general-kubernetes.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/upgrade-a-tidb-cluster.md
*: disable telemetry by default
=> *: disable telemetry by default

en/suspend-tidb-cluster.md, zh/suspend-tidb-cluster.md
English version of [PR 2004](https://github.com/pingcap/docs-tidb-operator/pull/2004)
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/2004
=> add-en-suspend-tidb-cluster

en/cheat-sheet.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
=> en,zh: bump operator to v1.4.3

en/advanced-statefulset.md, en/aggregate-multiple-cluster-monitor-data.md, en/backup-to-s3.md, en/cheat-sheet.md, en/configure-storage-class.md, en/deploy-on-alibaba-cloud.md, en/deploy-on-aws-eks.md, en/deploy-on-azure-aks.md, en/deploy-on-gcp-gke.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/advanced-statefulset.md, zh/aggregate-multiple-cluster-monitor-data.md, zh/backup-to-s3.md, zh/cheat-sheet.md, zh/configure-storage-class.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-on-aws-eks.md, zh/deploy-on-azure-aks.md, zh/deploy-on-gcp-gke.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
=> en,zh: bump operator to v1.4.3 for release-1.4

en/TOC.md, en/releases/release-1.4.3.md, zh/TOC.md, zh/releases/release-1.4.3.md
=> en,zh: release note for 1.4.3

en/TOC.md, en/releases/release-1.3.10.md, zh/TOC.md, zh/releases/release-1.3.10.md
=> en,zh: release note for 1.3.10

en/backup-to-aws-s3-by-snapshot.md, en/restore-from-aws-s3-by-snapshot.md, zh/backup-to-aws-s3-by-snapshot.md, zh/restore-from-aws-s3-by-snapshot.md
a new note to remind user of KMS TiKV encryption at rest
close #2220 
=> zh/en: add br notes to remind user of KMS TiKV encryption at rest

en/clinic-user-guide.md, en/deploy-tidb-operator.md, zh/clinic-user-guide.md, zh/deploy-tidb-operator.md
close https://github.com/pingcap/docs-tidb-operator/issues/2237
=> en,zh: fix dead external links

en/pd-recover.md, zh/pd-recover.md
1. fix wrong URL link
2. simplify step 4
3. simplify step 5
=> improve pd recover step

en/upgrade-tidb-operator.md, zh/upgrade-tidb-operator.md
=> fix-upgrade-tidb-operator

en/deploy-tidb-cluster-across-multiple-kubernetes.md
=> en: fix a typo in upgrading steps

en/TOC.md, en/releases/release-1.4.4.md, zh/TOC.md, zh/releases/release-1.4.4.md
=> en,zh: release note for 1.4.4

templates/copyright.tex
Update the date in copyright from 2019 to 2023
=> update the copyright date to 2023

templates/copyright.tex
Fix the typo in copyright.tex from "Reversed" to "Reserved".
=> fix the typo in copyright.tex

.github/workflows/dispatch.yml
=> remove dispatching to website-docs

en/access-dashboard.md, en/get-started.md, zh/access-dashboard.md, zh/get-started.md
close https://github.com/pingcap/docs-tidb-operator/issues/2305
=> *: wrap links in backticks

en/cheat-sheet.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
```
find . -type f | xargs sed -i "s/v1.4.4/v1.5.0-beta.1/g"
```
=> en,zh: bump operator to v1.5.0-beta.1

.github/pull_request_template.md, LICENSE, README.md
Update the LICENSE to [CC BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/)
=> *: update license to CC BY-SA 3.0

zh/enable-tls-for-mysql-client.md
=> fix tls link

en/deploy-heterogeneous-tidb-cluster.md
Fix typo in deploy-heterogeneous-tidb-cluster.md
=> fix typo in deploy-heterogeneous-tidb-cluster

en/restore-from-azblob-using-br.md, zh/restore-from-azblob-using-br.md
=> br: change the permission for external storage when do restore

en/releases/release-1.4.0.md, zh/releases/release-1.4.0.md
=> *: fix 1.4 release notes

en/upgrade-a-tidb-cluster.md, zh/upgrade-a-tidb-cluster.md
Add compatibility notes in the upgrade doc.
=> add compatibility notes in upgrade doc

en/deploy-ticdc.md, zh/deploy-ticdc.md
=> fix ticdc docs

en/_index.md, en/clinic-user-guide.md, en/tidb-operator-overview.md, zh/_index.md, zh/tidb-operator-overview.md
- on-premises -> self-hosted
- 私有部署 -> 自托管
=> *: unify terms

zh/_index.md, zh/tidb-operator-overview.md
=> fix table header for tidb/operator versions

en/clinic-user-guide.md, zh/clinic-user-guide.md
update clinic doc, let customer get newly diag version first and install newly version
=> en,zh: use variable to indicate clinic version

en/TOC.md, en/releases/release-1.4.5.md, zh/TOC.md, zh/releases/release-1.4.5.md
=> en,zh: release note for 1.4.5

en/advanced-statefulset.md, en/aggregate-multiple-cluster-monitor-data.md, en/backup-to-s3.md, en/cheat-sheet.md, en/configure-storage-class.md, en/deploy-on-alibaba-cloud.md, en/deploy-on-aws-eks.md, en/deploy-on-azure-aks.md, en/deploy-on-gcp-gke.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/advanced-statefulset.md, zh/aggregate-multiple-cluster-monitor-data.md, zh/backup-to-s3.md, zh/cheat-sheet.md, zh/configure-storage-class.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-on-aws-eks.md, zh/deploy-on-azure-aks.md, zh/deploy-on-gcp-gke.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
```base
find . -type f | xargs sed -i "s/v1.4.4/v1.4.5/g"
```
=> en,zh: bump operator to v1.4.5 for release-1.4

en/configure-a-tidb-cluster.md, zh/configure-a-tidb-cluster.md
Close https://github.com/pingcap/docs-tidb-operator/issues/2398
=> fix the configuration format in multiple disks mounting

en/configure-storage-class.md, en/get-started.md
=> en: optimize 2 docs

en/TOC.md, en/releases/release-1.4.6.md, zh/TOC.md, zh/releases/release-1.4.6.md
=> en,zh: release note for v1.4.6

en/backup-to-aws-s3-by-snapshot.md, zh/backup-to-aws-s3-by-snapshot.md
=> en,zh: add resolved-ts configuration to EBS backup limitations

en/TOC.md, en/releases/release-1.4.7.md, zh/TOC.md, zh/releases/release-1.4.7.md
=> en,zh: release note for v1.4.7

en/advanced-statefulset.md, en/aggregate-multiple-cluster-monitor-data.md, en/backup-to-s3.md, en/cheat-sheet.md, en/configure-storage-class.md, en/deploy-on-alibaba-cloud.md, en/deploy-on-aws-eks.md, en/deploy-on-azure-aks.md, en/deploy-on-gcp-gke.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/advanced-statefulset.md, zh/aggregate-multiple-cluster-monitor-data.md, zh/backup-to-s3.md, zh/cheat-sheet.md, zh/configure-storage-class.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-on-aws-eks.md, zh/deploy-on-azure-aks.md, zh/deploy-on-gcp-gke.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
execute the command find . -type f | xargs gsed -i "s/v1.4.6/v1.4.7/g" to bump operator version to v1.4.7
=> en,zh: bump operator to v1.4.7

en/cheat-sheet.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
```bash
find . -type f | xargs sed -i "s/v1.5.0-beta.1/v1.5.0/g"
```
=> en,zh: bump operator to v1.5.0

README.md
=> update readme for v1.5 GA

zh/grant-permissions-to-remote-storage.md
Remove some spaces in the option, which cause "error: unknown flag: --from-", when create secrete from command line.
=> Remove spaces in options

en/TOC.md, en/releases/release-1.5.1.md, zh/TOC.md, zh/releases/release-1.5.1.md
=> en,zh: add v1.5.1 release notes

zh/configure-a-tidb-cluster.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/2448
=> Clarify use of topologySpreadConstraints 

en/TOC.md, en/configure-a-tidb-cluster.md, en/deploy-failures.md, en/deploy-on-general-kubernetes.md, en/deploy-tidb-cluster-across-multiple-kubernetes.md, en/deploy-tiproxy.md, en/enable-tls-between-components.md, en/faq.md, en/modify-tidb-configuration.md, en/renew-tls-certificate.md, en/scale-a-tidb-cluster.md, en/suspend-tidb-cluster.md, en/upgrade-a-tidb-cluster.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/2477
=> en: add tiproxy docs

en/TOC.md, en/releases/release-1.5.2.md, zh/TOC.md, zh/releases/release-1.5.2.md
=> en,zh: add v1.5.2 release notes

en/cheat-sheet.md, en/deploy-br-federation.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
```bash
find . -type f | xargs sed -i "s/v1.5.1/v1.5.2/g"
git checkout -- zh/whats-new-in-v1.5.md en/whats-new-in-v1.5.md
```
=> en,zh: bump operator to v1.5.2

en/releases/release-1.5.2.md
=> en: fix release 1.5.2

en/scale-a-tidb-cluster.md, zh/scale-a-tidb-cluster.md
=> scale-a-tidb-cluster: fix pd micro service indent

en/advanced-statefulset.md, en/clinic-user-guide.md, en/configure-a-tidb-cluster.md, en/configure-storage-class.md, en/deploy-br-federation.md, en/deploy-on-alibaba-cloud.md, en/deploy-on-azure-aks.md, en/deploy-tidb-dm.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/enable-admission-webhook.md, en/get-started.md, en/prerequisites.md, en/upgrade-tidb-operator.md, zh/advanced-statefulset.md, zh/clinic-user-guide.md, zh/configure-a-tidb-cluster.md, zh/configure-storage-class.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-on-azure-aks.md, zh/deploy-tidb-dm.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/enable-admission-webhook.md, zh/get-started.md, zh/prerequisites.md, zh/upgrade-tidb-operator.md
bump K8s version to v1.24, as we bumped the k8s Golang mod to v1.28 (and k8s v1.24 is also End of Life)
=> bump k8s version to v1.24

en/_index.md, zh/_index.md
=> _index: update links for deploy-on-azure-aks

en/exceptions.md, zh/exceptions.md
=> en, zh: fix code typo in exceptions

en/TOC.md, en/releases/release-1.5.3.md, zh/TOC.md, zh/releases/release-1.5.3.md
=> en,zh: add v1.5.3 release notes

en/TOC.md, en/releases/release-1.6.0.md, en/whats-new-in-v1.6.md, zh/TOC.md, zh/releases/release-1.6.0.md, zh/whats-new-in-v1.6.md
=> en,zh: add v1.6 GA release notes and whats new

README.md, en/_index.md, zh/_index.md
=> v1.6 learning path: bump up version to v1.6

en/_index.md, en/clinic-user-guide.md, en/tidb-operator-overview.md
self-hosted → self-managed
- https://github.com/pingcap/docs-cn/pull/18520
- https://github.com/pingcap/docs-tidb-operator/pull/2370
=> en: unify product terms

en/deploy-on-gcp-gke.md, en/prerequisites.md, zh/deploy-on-gcp-gke.md, zh/prerequisites.md
update CentOS 7 related description
=> update CentOS 7 related description

en/scale-a-tidb-cluster.md, zh/scale-a-tidb-cluster.md
=> pdms: correct scale command

en/TOC.md, en/releases/release-1.6.1.md, zh/TOC.md, zh/releases/release-1.6.1.md
=> en,zh: add v1.6.1 release notes

.github/pull_request_template.md, README.md
=> archive v1.2

en/releases/release-1.3.0-beta.1.md, zh/releases/release-1.1-ga.md
=> remove unnecessary white space

en/get-started.md, zh/get-started.md
=> zh,en: remove tidb-scheduler in get-started

.github/workflows/media.yml
=> ci: upload media to cos

.github/workflows/media.yml
=> fix(ci): cdn refresh

en/restart-a-tidb-cluster.md, zh/restart-a-tidb-cluster.md
增加了优雅重启关于 Flush Log Backup 的部分。
Added description of auto flushing log backup when doing graceful restarting.
- Other reference link(s): https://github.com/pingcap/tidb-operator/pull/6057
=> added flush log backup tasks

en/TOC.md, zh/TOC.md
=> toc: fix links

.github/pull_request_template.md
=> pull_request_template.md: add v2

zh/TOC.md, zh/containers-run-as-non-root-user.md
=> Add a doc about how to run as non root user

zh/TOC.md, zh/destroy-a-tidb-cluster.md, zh/view-logs.md
=> zh: Add docs about how to destroy a tidb cluster and how to view logs

en/TOC.md, en/destroy-a-tidb-cluster.md, en/view-logs.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/2743
=> en: Add docs about how to destroy a tidb cluster and how to view logs

zh/TOC.md, zh/restart-a-tidb-cluster.md
=> zh: how to restart a tidb cluster

en/TOC.md, en/restart-a-tidb-cluster.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/2751
=> en: how to restart a tidb cluster

zh/TOC.md, zh/access-tidb.md, zh/deploy-failures.md, zh/exceptions.md, zh/scale-a-tidb-cluster.md
=> zh: scale a tidb cluster

en/TOC.md, en/tidb-toolkit.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/2763
- Other reference link(s):  https://docs.pingcap.com/tidb-in-kubernetes/stable/tidb-toolkit/
=> en: tidb toolkit

en/TOC.md, en/restart-a-tidb-cluster.md, zh/TOC.md, zh/enable-tls-between-components.md
=> zh: enable tls between components

en/TOC.md, en/access-tidb.md, zh/TOC.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/2745
=> en: how to access tidb 

en/TOC.md, en/kubernetes-observability.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/2761
=> en: k8s observability

zh/backup-to-azblob-using-br.md, zh/restore-from-azblob-using-br.md
=> zh: restore from azure

zh/configure-volume.md
=> zh: configure and modify volumes

en/TOC.md, en/suspend-tidb-cluster.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/2754
=> en: how to suspend a tidb cluster

en/TOC.md, en/backup-restore-cr.md, en/backup-restore-overview.md, en/backup-to-aws-s3-using-br.md, en/backup-to-azblob-using-br.md, en/backup-to-gcs-using-br.md, en/backup-to-pv-using-br.md, en/restore-from-aws-s3-using-br.md, en/restore-from-azblob-using-br.md, en/restore-from-gcs-using-br.md, en/restore-from-pv-using-br.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/2768
=> en: backup restore overview

en/TOC.md, en/backup-to-azblob-using-br.md, en/restore-from-azblob-using-br.md, zh/restore-from-azblob-using-br.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/2792
=> en: restore from azure

en/TOC.md, en/volume-configuration.md, zh/configure-volume.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/2803
=> en: configure and modify volumes

en/TOC.md, en/backup-to-azblob-using-br.md, zh/backup-to-azblob-using-br.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/2790
=> en: backup to azblob

en/TOC.md, en/restore-from-gcs-using-br.md, zh/restore-from-gcs-using-br.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/2789
=> en: restore from gcs using br

zh/_index.md
=> zh: add learning path

en/_index.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/2831
=> en: add learning path

en/TOC.md, en/upgrade-a-tidb-cluster.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/2801
=> en: upgrade a tidb cluster

en/TOC.md, en/upgrade-tidb-operator.md
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/2798
=> en: upgrade tidb operator

.github/pull_request_template.md, README.md, en/TOC.md, en/releases/release-2.0.0-beta.0.md, zh/TOC.md, zh/releases/release-2.0.0-beta.0.md
- Add `release-2.0` and `feature/v2` to README.md and `.github/pull_request_template.md`
- Use 2-space indentation in `TOC.md`
- Update the release date in `release-2.0.0-beta.0.md`
=> release: init v2

en/component-configuration.md, zh/component-configuration.md
=> zh, en: remove HotReload policy in doc

en/scale-a-tidb-cluster.md, zh/scale-a-tidb-cluster.md
=> zh, en: add notes for in place pod resize

en/access-tidb.md, en/deploy-tidb-cluster.md, en/scale-a-tidb-cluster.md, zh/access-tidb.md, zh/deploy-tidb-cluster.md, zh/scale-a-tidb-cluster.md
=> en, zh: fix some issues

en/TOC.md, variables.json, zh/TOC.md
=> variables: update tidb_operator_version to v2.0.0-beta.0

scripts/merge_by_toc.py
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/20618
=> ci: add variable replacement and custom ID handling

en/TOC.md, en/releases/release-1.6.2.md, zh/TOC.md, zh/releases/release-1.6.2.md
=> en,zh: add v1.6.2 release notes

.github/workflows/media.yml
=> ci: add feature/v2 branch to push triggers

en/releases/release-1.6.2.md
=> en: fix format of release-1.6.2

en/renew-tls-certificate.md
=> en: fix format in renew-tls-certificate.md

en/TOC.md, en/releases/release-1.6.3.md, variables.json, zh/TOC.md, zh/releases/release-1.6.3.md
Add v1.6.3 release notes and bump TiDB Operator to v1.6.3
=> en,zh: bump operator to v1.6.3 and add release notes

en/TOC.md, en/exceptions.md, en/scale-a-tidb-cluster.md, zh/TOC.md, zh/exceptions.md, zh/scale-a-tidb-cluster.md
=> Add Common Cluster Exception

en/get-started.md, zh/get-started.md
=> Remove note about TiDB < v4.0.7
