pingcap/docs-tidb-operator

zh/backup-to-aws-s3.md, zh/restore-from-aws-s3.md
Add backup and restore AWS TiDB Cluster with BR tool.
use the latest TiDB Operator and these changes will apply to release 1.1
Add backup and restore AWS TiDB Cluster with BR tool.
ons)
for preview:
https://github.com/shuijing198799/docs-tidb-operator/blob/master/zh/backup-to-aws-s3.md
https://github.com/shuijing198799/docs-tidb-operator/blob/master/zh/restore-from-aws-s3.md
=> zh: add backup and restore aws br doc

zh/deploy-on-alibaba-cloud.md
deploy tidb cluster on ack with cr
=> zh: update doc for deploy tidb cluster on ack with cr

.github/pull_request_template.md
Add v1.1 version in PR template.
=> .github: add v1.1 version in PR template

zh/backup-to-aws-s3-using-br.md, zh/restore-from-aws-s3-using-br.md
- Fix typo in backup and restore using BR.
- Remove extra spaces.
=> zh: fix typo in backup and restore using br

en/deploy-on-alibaba-cloud.md
Update doc for deploying TiDB cluster on Alibaba cloud.
- This PR is translated from:  https://github.com/pingcap/docs-tidb-operator/pull/30
=> en: update doc for deploying TiDB cluster on ACK

zh/TOC.md, zh/advanced-statefulset.md, zh/using-advanced-statefulset.md
=> zh: add Advanced StatefulSet

en/TOC.md, en/enable-tls-between-components.md, en/enable-tls-for-mysql-client.md
- Add doc for enabling TLS between TiDB components
- Fix an error in the `enable TLS for mysql client` doc
- This PR is translated from:  https://github.com/pingcap/docs-tidb-operator/pull/39
=> en: add doc for enable TLS between TiDB components

en/enable-tls-between-components.md, en/enable-tls-for-mysql-client.md
Replace `ClusterIssuer` with `Issuer` in TidbCluster.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/150
=> en: use Issuer instead of ClusterIssuer in TLS docs

en/enable-tls-between-components.md
The `commonName` in all `certificate` objects should be the same.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/167
=> en: fix commonName of all certificate

en/enable-tls-for-mysql-client.md, zh/enable-tls-for-mysql-client.md
We need to add the following DNS names to certificate, otherwise dashboard will not work if TLS is enabled.
```
- "*.${cluster_name}-tidb-peer"
- "*.${cluster_name}-tidb-peer.${namespace}"
- "*.${cluster_name}-tidb-peer.${namespace}.svc"
```
=> zh, en: update dns names list in tls certificate

en/enable-tls-between-components.md, en/enable-tls-for-mysql-client.md, zh/enable-tls-between-components.md, zh/enable-tls-for-mysql-client.md
Some of tls features are missing in 3.0.8 such as `cert-allowed-cn` configuration. So the example in the document will fail. This PR changes it to 3.1.0 which should work normally.
=> zh, en: use 3.1 in tls related documents

zh/pd-recover.md
Rewording the cluster id in pd-recover.md to make it clearer.
=> zh: rewording for cluster id

zh/backup-to-gcs.md, zh/backup-to-s3.md
Update CRD backup docs with mydumper.
pingcap/tidb-operator#2435
pingcap/tidb-operator#2407
=> zh: Update mydumper backup docs

zh/enable-tls-for-mysql-client.md
ref: https://github.com/pingcap/tidb-operator/issues/2404, add document separate client certificates for each components.
=> zh: separate client certificates for each component

zh/backup-to-gcs.md
Fix [typo](https://github.com/pingcap/docs-tidb-operator/pull/273/files#r430968448)
=> zh: fix a typo in backup-to-gcs

en/get-started.md
`deploy-tidb-from-kubernetes-kind.md` and `deploy-tidb-from-kubernetes-minikube.md` have been reorganized and merged into `get-started.md`.
We need to add aliases to avoid 404 error.
=> en: add aliases in get-started

en/configure-a-tidb-cluster.md, en/deploy-on-alibaba-cloud.md, en/deploy-on-aws-eks.md, en/deploy-tiflash.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-on-aws-eks.md, zh/deploy-on-general-kubernetes.md, zh/deploy-tiflash.md
=> en, zh: add warning for configuring multiple pvs for tiflash

en/deploy-on-aws-eks.md
Translate https://github.com/pingcap/docs-tidb-operator/pull/421
- This PR is translated from:  https://github.com/pingcap/docs-tidb-operator/pull/421
- Other reference link(s): https://github.com/pingcap/tidb-operator/pull/2714
=> en: update the eks deployment doc

en/configure-a-tidb-cluster.md, zh/get-started.md
When a previous PR (https://github.com/pingcap/docs-tidb-operator/pull/328) deleted configure-tidb-using-tidbcluster.md, it didn't add an alias to redirect.
=> add aliases in 2 docs

en/deploy-tidb-binlog.md
Document how to set tls config between drainer and upstream database.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/589
=> en: set TLS config between drainer and downstream

en/configure-a-tidb-cluster.md, en/deploy-on-alibaba-cloud.md, en/deploy-on-aws-eks.md, en/deploy-on-gcp-gke.md, en/deploy-ticdc.md, en/deploy-tidb-binlog.md, en/deploy-tiflash.md, en/upgrade-a-tidb-cluster.md
Add enterprise image in deployment/upgrade docs.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/529
=> en: add enterprise image in deployment/upgrade docs

zh/backup-to-aws-s3-using-br.md, zh/backup-to-gcs-using-br.md, zh/backup-to-gcs.md, zh/backup-to-s3.md, zh/deploy-failures.md, zh/restore-from-aws-s3-using-br.md, zh/restore-from-gcs-using-br.md, zh/restore-from-gcs.md, zh/restore-from-s3.md
Add debug section for backup restore part. Comment `storageClassName` in backup & restore to avoid mistake.
=> zh: add debug section for backup restore, comment storageClassName by default

zh/access-dashboard.md, zh/access-tidb.md, zh/advanced-statefulset.md, zh/backup-to-aws-s3-using-br.md, zh/backup-to-gcs-using-br.md, zh/backup-to-gcs.md, zh/backup-to-s3.md, zh/configure-a-tidb-cluster.md, zh/deploy-on-gcp-gke.md, zh/deploy-on-general-kubernetes.md, zh/deploy-tidb-binlog.md, zh/deploy-tidb-enterprise-edition.md, zh/enable-tls-between-components.md, zh/enable-tls-for-mysql-client.md, zh/monitor-using-tidbmonitor.md, zh/notes-tidb-operator-v1.1.md, zh/pd-recover.md, zh/restart-a-tidb-cluster.md, zh/restore-data-using-tidb-lightning.md, zh/restore-from-aws-s3-using-br.md, zh/restore-from-gcs-using-br.md, zh/restore-from-gcs.md, zh/upgrade-a-tidb-cluster.md
https://github.com/pingcap/docs-tidb-operator/issues/671
TiDB-operator has updated backup and restore table filters in https://github.com/pingcap/tidb-operator/pull/3134. This PR will also update the usage of table filter and bump tidb version to v4.0.6.
=> zh: update backup & restore table filter usage and bump tidb cluster version to v4.0.6

en/TOC.md, en/releases/release-1.1.5.md, zh/TOC.md, zh/releases/release-1.1.5.md
=> zh, en: release tidb-operator v1.1.5

en/TOC.md, en/releases/release-1.1.7.md, zh/TOC.md, zh/releases/release-1.1.7.md
Add release notes for TiDB-Operator v1.1.7
- Other reference link(s): https://github.com/pingcap/tidb-operator/issues/3495
None
=> en, zh: add release notes for v1.1.7

.circleci/config.yml, scripts/merge_by_toc.py
Remove `copyable `code snippet when generate PDF.
=> chore: remove copyable snippet code when generate PDF

zh/access-dashboard.md
For those don't have available domain configured, an option to access Dashboard would be using `Service` with `NodePort` type. This PR adds an example for it.
=> zh: add example to access dashboard via NodePort Service

en/maintain-a-kubernetes-node.md, en/tips.md, en/use-tkctl.md, zh/maintain-a-kubernetes-node.md, zh/tips.md, zh/use-tkctl.md
**why the third target is not done?**
The origin docs didn't offer any alternative `kubectl` commands ("network-issues.md") and I don't know how to get the result in the docs.
The `tkctl` tool is no longer usable, update the relevant docs.
- Other reference link(s): https://github.com/pingcap/docs-tidb-operator/issues/908
=> en, zh: v1.1 abandon "tkctl" tool

en/access-dashboard.md, zh/access-dashboard.md
For those don't have available domain configured, an option to access Dashboard would be using `Service` with `NodePort` type.
- This PR is translated from:  https://github.com/pingcap/docs-tidb-operator/pull/850
=> en: Add an example to access dashboard via NodePort Service

en/TOC.md, en/releases/release-1.1.8.md, zh/TOC.md, zh/releases/release-1.1.8.md
Add release notes for TiDB-Operator v1.1.8
- https://github.com/pingcap/tidb-operator/issues/3616
=> en, zh: add release notes for v1.1.8

en/cheat-sheet.md, en/configure-storage-class.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/configure-storage-class.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
bump tidb operator charts version to v1.1.8
```
find . -type f | xargs sed -i "s/v1.1.7/v1.1.8/g"
```
ref #851
- https://github.com/pingcap/tidb-operator/issues/3616
=> en, zh: bump TiDB Operator charts version to v1.1.8

zh/maintain-a-kubernetes-node.md
在第 187 行 添加选项 “--wait=false” ，否则由于 pod 一直在使用该 PVC 无法删除
=> add option "--wait=false" when delete PVC

en/enable-tls-between-components.md, en/enable-tls-for-dm.md, en/enable-tls-for-mysql-client.md, zh/enable-tls-between-components.md, zh/enable-tls-for-dm.md, zh/enable-tls-for-mysql-client.md
update the CA expiration date to 10 years for cfssl (default 5 years) and cert-manager (default 90 days)
close #980
=> zh, en: update the CA expiration date to 10 years

en/cheat-sheet.md, en/configure-storage-class.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/configure-storage-class.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-on-aws-eks.md, zh/deploy-on-gcp-gke.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
Bump Operator to v1.1.10 and TiDB components to v4.0.10.
This PR bumps operator to v1.1.10, TiDB components are bumped in PR #1087 .
ref #976 
Run commands:
```shell
find . -type f | xargs sed -i "s/v1.1.9/v1.1.10/g"
```
=> en,zh; Bump Operator to v1.1.10

en/cheat-sheet.md, en/configure-storage-class.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/configure-storage-class.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-on-aws-eks.md, zh/deploy-on-gcp-gke.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
Bump Operator to v1.1.11.
ref #1088
Run commands:
```bash
find . -type f | xargs sed -i "s/v1.1.9/v1.1.10/g"
```
=> en, zh: Bump Operator to v1.1.11

en/cheat-sheet.md, en/configure-storage-class.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/configure-storage-class.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-on-aws-eks.md, zh/deploy-on-gcp-gke.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
Bump Operator to v1.1.12
ref #1108
Run commands:
```shell
find . -type f | xargs sed -i "s/v1.1.11/v1.1.12/g"
```
=> en, zh: Bump Operator to v1.1.12

en/enable-tls-for-dm.md, zh/enable-tls-for-dm.md
dmctl can't support `http://` as master addr. close https://github.com/pingcap/dm/issues/1459
=> en,zh: fix wrong dmctl command

en/get-started.md
Add alias for `kubectl` via `minikube`
The `--` is needed to pass arguments to `kubectl` instead of `minikube`
=> get-started: add alias for kubectl in minikube

en/backup-to-s3.md, en/deploy-on-aws-eks.md
- Use `tidb-cluster` as namespace instead of `test1`.
This matches the namespace created by
https://docs.pingcap.com/tidb-in-kubernetes/stable/deploy-on-aws-eks#create-namespace
- Change link to raw version of `backup-rbac.yaml` and directly specify
it in the `kubectl` command
- Try to make the database permissions easier to read and apply.
- Add a note about the different methods for authentication
- Add information about describing backup jobs
- Add info about running an ad-hoc backup job again by first deleting it.
- Add info about verifying AWS access
- Add info about name constraints for the cluster and node group names
This can safe a lot of time as it otherwise fails late in the process if `_` is used.
- Change the expected time for cluster creating from 5 to 10 minutes to 5 to 20 …
=> en: backup-to-s3, deploy-on-aws-eks: various small changes

en/deploy-ticdc.md, zh/deploy-ticdc.md
Use the recommended method to enter a TiCDC Pod.
> kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
=> en, zh: Use the recommended method to enter a TiCDC Pod

en/prerequisites.md, zh/prerequisites.md
Use drop-in directory to configure docker service.
Closes #1257 
=> zh,en: Use drop-in directory to configure docker service

en/TOC.md, en/releases/release-1.1.13.md, zh/TOC.md, zh/releases/release-1.1.13.md
=> en, zh: add release notes for v1.1.13

en/TOC.md, en/releases/release-1.2.0.md, zh/TOC.md, zh/releases/release-1.2.0.md
=> en, zh: add release notes for v1.2.0

en/cheat-sheet.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
Bump Operator to v1.2.1
ref #1330
Run commands:
```shell
find . -type f | xargs sed -i "s/v1.2.0/v1.2.1/g"
```
=> en, zh: Bump Operator to v1.2.1

en/cheat-sheet.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
Bump Operator to v1.2.3
ref #1363
Run commands:
```shell
find . -type f | xargs sed -i "s/v1.2.1/v1.2.3/g"
```
=> en,zh; Bump Operator to v1.2.3

.circleci/config.yml
The markdown lint check in Circleci is duplicated in git action workflow, so remove lint check from circleci.
=> chore: remove markdown lint from circleci

en/deploy-on-alibaba-cloud.md, en/deploy-on-aws-eks.md, en/deploy-on-gcp-gke.md, en/deploy-tidb-from-kubernetes-gke.md, en/enable-tls-for-mysql-client.md, en/get-started.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-on-aws-eks.md, zh/deploy-on-gcp-gke.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/enable-tls-for-mysql-client.md, zh/get-started.md
With TIDB in general `--comments` is needed. This is because without that option comments are stripped before they are sent to the server. This causes problems as TiDB specific code like `/*T![clustered_index] CLUSTERED */` for TiDB and TiDB feature specific parts of statements. This is used by `SHOW CREATE TABLE...` etc.
While it might not be strictly required here, it would be good to add it anyway as it is a best practice to use `--comments` for all TiDB sessions as forgetting this might cause statements to silently behave differently which can be very frustrating for users and cause all kinds of issues. And you never know what a user might use the session for after doing this step of the docs.
=> en,zh: Use `mysql --comments` everywhere

en/TOC.md, en/releases/release-1.2.5.md, zh/TOC.md, zh/releases/release-1.2.5.md
=> en,zh: add release notes for v1.2.5

en/TOC.md, en/releases/release-1.3.0-beta.1.md, zh/TOC.md, zh/releases/release-1.3.0-beta.1.md
=> en,zh: Add release notes for v1.3.0-beta.1

en/cheat-sheet.md, en/deploy-cluster-on-arm64.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/deploy-cluster-on-arm64.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
=> en,zh; bump tidb operator to v1.3.0

en/cheat-sheet.md, en/deploy-cluster-on-arm64.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/deploy-cluster-on-arm64.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
Run commands and some manual fix:
```shell
find . -type f | xargs sed -i "s/v1.3.0/v1.3.1/g"
```
=> en,zh: Bump operator to v1.3.1

en/TOC.md, en/releases/release-1.3.0-beta.1.md, en/releases/release-1.3.0.md, en/releases/release-1.3.1.md, en/whats-new-in-v1.3.md, zh/TOC.md, zh/releases/release-1.3.0-beta.1.md, zh/releases/release-1.3.0.md, zh/releases/release-1.3.1.md, zh/whats-new-in-v1.3.md
=> en, zh: add release notes for v1.3.1

en/deploy-heterogeneous-tidb-cluster.md, en/monitor-a-tidb-cluster.md, zh/deploy-heterogeneous-tidb-cluster.md, zh/monitor-a-tidb-cluster.md
bump prometheus version to v2.27.1 and grafana to 7.5.11
close #1459 
=> monitor: bump prometheus version to v2.27.1 and grafana to 7.5.11

en/deploy-on-gcp-gke.md, zh/deploy-on-gcp-gke.md
The original doc will cause someone don't familiar with GKE be confused, and spend more time on the deployment a correct cluster.
After changing the doc, we also need to consider to give a default storageclass setup in https://raw.githubusercontent.com/pingcap/tidb-operator/master/examples/gcp/tidb-cluster.yaml
If we don't give default sc to pd-ssd, we will also need to step, to tell the user they need to change the default sc type in the yaml for best practice.
=> Update storage class description for GKE deploy

en/tidb-scheduler.md, zh/tidb-scheduler.md
Signed-off-by: Aolin <aolin.zhang@pingcap.com>
Close https://github.com/pingcap/docs-tidb-operator/issues/1864
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/scheduling/scheduler_extender.md has been removed in https://github.com/kubernetes/community/pull/6591.
=> Fix 404 link: Kubernetes scheduler extender

en/cheat-sheet.md, en/deploy-on-alibaba-cloud.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/cheat-sheet.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
```shell
find . -type f | xargs sed -i "s/v1.3.3/v1.3.4/g"
```
=> bump operator to 1.3.6

en/backup-to-aws-s3-using-br.md, en/backup-to-gcs-using-br.md, zh/backup-to-aws-s3-using-br.md, zh/backup-to-gcs-using-br.md
the sample code in [scheduled-full-backup](https://docs.pingcap.com/tidb-in-kubernetes/stable/backup-to-aws-s3-using-br#step-2-perform-a-scheduled-full-backup) only mentioned `#maxBackups: 5` and `maxReservedTime: "3h"`, but **it only delete `backup CR`**, if user also want clean outdated backup data in S3 or GCS they need config `spec.backupTemplate.cleanPolicy: Delete`, which maybe missed because user already config the `#maxBackups: 5` and `maxReservedTime: "3h"` as sample code show.
This PR add comment for `cleanPolicy: Delete` in the sample code.
=> add cleanPolicy for BackupSchedule

en/monitor-a-tidb-cluster.md, zh/monitor-a-tidb-cluster.md
根据官网文档[多集群监控](https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/monitor-a-tidb-cluster#%E5%A4%9A%E9%9B%86%E7%BE%A4%E7%9B%91%E6%8E%A7) 部署后 grafana 上无法显示集群信息，发现是缺少 `clusterScoped: true` 的配置。
参考 operator release 对于 clusterScoped 的说明
参考 operator github example [monitor-multiple-cluster-non-tls](https://github.com/pingcap/tidb-operator/blob/master/examples/monitor-multiple-cluster-non-tls/tidb-monitor.yaml)
=> add clusterScoped for monitor multiple clusters

README.md, en/releases/release-1.0-ga.md, en/releases/release-1.0.4.md, zh/configure-a-tidb-cluster.md, zh/deploy-failures.md, zh/deploy-ticdc.md, zh/deploy-tidb-binlog.md, zh/enable-tls-for-mysql-client.md, zh/faq.md, zh/monitor-a-tidb-cluster.md, zh/pd-recover.md, zh/prerequisites.md, zh/releases/release-1.0-ga.md, zh/releases/release-1.0.4.md, zh/restore-data-using-tidb-lightning.md, zh/restore-from-aws-s3-using-br.md, zh/tidb-toolkit.md
Signed-off-by: Ran <huangran.alex@gmail.com>
The old links redirect users to v4.0 TiDB docs. I'm updating them to use the stable version of TiDB docs.
=> update all old links for docs.pingcap.com

en/TOC.md, zh/TOC.md
Added the index page to left navigation (TOC), providing a place for uses to go back to the index page (the home of TiDB Operator docs of that version), for omitted versions in #2073 
- Other reference link(s):  #2073
=> en, zh: add index page to left navigation

en/clinic-user-guide.md, zh/clinic-user-guide.md
If user's environment do not allow public connection, for example like AWS EC2 with no public network gateway, or AWS EKS cluster with [`privateNetworking: true`](https://eksctl.io/usage/schema/#managedNodeGroups-privateNetworking), which is also recommended in [our doc](https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/deploy-on-aws-eks#%E5%88%9B%E5%BB%BA-eks-%E9%9B%86%E7%BE%A4%E5%92%8C%E8%8A%82%E7%82%B9%E6%B1%A0), then we can not directly access the clinic diag service, the workaround is use `port-forward` command to redirect the service port to the local, so we can send request to the local service proxy.
=> add-port-forward-in-clinic-doc

en/build-multi-aws-eks.md, zh/build-multi-aws-eks.md
1. there has a wrong `space` in the command and cause command execute failed 
2. lack `-n ${namespace_1}` in command
=> en,zh: fix command in multi aws eks

en/backup-restore-cr.md, en/backup-to-aws-s3-using-br.md, en/backup-to-azblob-using-br.md, en/backup-to-gcs-using-br.md
as title.
- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/2236
=> en: add doc for Backoff retry policy and auto truncate log backup by backupschedule

en/deploy-tiflash.md
Fixed the typo
Fixed the typo `eidt` to `edit` in the docs
=> Typo in the kubectl edit command

en/deploy-on-aws-eks.md, zh/deploy-on-aws-eks.md
New deployed EKS cluster may use newly Kubernetes 1.24 version, and from Kubernetes 1.23 the in-tree plugins seems is deprecated, see [important note in EKS Kubernetes 1.23](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.23), so user can not directly deploy TiDB cluster using gp2 disk after EKS cluster created.
Add a note for this in operator doc, if user use EKS cluster  Kubernetes version >= 1.23, need follow [Amazon EBS CSI driver doc](https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html) to deploy iam sa and EKS gp2 add-on first.
=> add-note-for-aws-gp2

.github/pull_request_template.md, .github/workflows/dispatch.yml, .github/workflows/link.yml
- Remove `v1.1` from the pull_request_template
- Update the `set-output` command to `$GITHUB_OUTPUT` (set-output is deprecated)
- Update `peter-evans/create-issue-from-file` from v3 to v4 (Node.js 12 actions (peter-evans/create-issue-from-file@v3) are deprecated)
- This PR is translated from: https://github.com/pingcap/docs-cn/pull/13612
=> update the deprecated set-output command

.github/workflows/link.yml, .github/workflows/media.yml, .github/workflows/vale.yaml
Node.js 12 actions and the `set-output` command are deprecated.
This PR updates the following actions to use Node.js 16:
- `actions/checkout@v2`
- `actions/setup-node@v1`
- `andstor/file-existence-action@v1`
=> ci: update specified actions to the latest

en/configure-a-tidb-cluster.md, zh/configure-a-tidb-cluster.md
HostNetwork link is broken, maybe https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy is more suitable.
=> fix-HostNetwork-link

en/advanced-statefulset.md, en/backup-restore-cr.md
Fix a typo and remove extra spaces
=> en: fix a typo and update format

en/advanced-statefulset.md, en/aggregate-multiple-cluster-monitor-data.md, en/backup-to-s3.md, en/cheat-sheet.md, en/configure-storage-class.md, en/deploy-on-alibaba-cloud.md, en/deploy-on-aws-eks.md, en/deploy-on-azure-aks.md, en/deploy-on-gcp-gke.md, en/deploy-tidb-from-kubernetes-gke.md, en/deploy-tidb-operator.md, en/get-started.md, en/tidb-toolkit.md, en/upgrade-tidb-operator.md, zh/advanced-statefulset.md, zh/aggregate-multiple-cluster-monitor-data.md, zh/backup-to-s3.md, zh/cheat-sheet.md, zh/configure-storage-class.md, zh/deploy-on-alibaba-cloud.md, zh/deploy-on-aws-eks.md, zh/deploy-on-azure-aks.md, zh/deploy-on-gcp-gke.md, zh/deploy-tidb-from-kubernetes-gke.md, zh/deploy-tidb-operator.md, zh/get-started.md, zh/tidb-toolkit.md, zh/upgrade-tidb-operator.md
execute the command `find . -type f | xargs gsed -i "s/v1.4.5/v1.4.6/g"` to bump operator version to v1.4.6
=> en,zh: bump operator to v1.4.6

en/configure-a-tidb-cluster.md
- Other reference link(s): [](https://docs.pingcap.com/tidb-in-kubernetes/stable/configure-a-tidb-cluster#use-topologyspreadconstraints-to-make-pods-evenly-spread)
=> Clarify use of topologySpreadConstraints

en/restore-data-using-tidb-lightning.md, en/tidb-toolkit.md, zh/restore-data-using-tidb-lightning.md, zh/tidb-toolkit.md
=> deprecated-tikv-importer-in-operator

zh/TOC.md, zh/configure-a-tidb-cluster.md, zh/deploy-cluster-on-arm64.md, zh/deploy-failures.md, zh/deploy-on-general-kubernetes.md, zh/deploy-tidb-cluster-across-multiple-kubernetes.md, zh/deploy-tiproxy.md, zh/enable-tls-between-components.md, zh/faq.md, zh/modify-tidb-configuration.md, zh/renew-tls-certificate.md, zh/scale-a-tidb-cluster.md, zh/suspend-tidb-cluster.md, zh/upgrade-a-tidb-cluster.md
=> tiproxy: add basic document

en/pd-recover.md, zh/pd-recover.md
When using alive PD to recreate pd cluster, there is no need to restart TiDB and TiKV, see TiUP related doc https://docs.pingcap.com/zh/tidb/stable/pd-recover#%E7%AC%AC-5-%E6%AD%A5%E6%89%A9%E5%AE%B9-pd-%E5%B9%B6%E5%90%AF%E5%8A%A8%E9%9B%86%E7%BE%A4
=> fix-pd-recover

en/deploy-on-aws-eks.md, en/deploy-on-azure-aks.md, en/deploy-on-gcp-gke.md, zh/deploy-on-aws-eks.md, zh/deploy-on-azure-aks.md, zh/deploy-on-gcp-gke.md
- Update storageClass mountOptions to 2 separate options, instead of separated by commas. 
- https://kubernetes.io/docs/concepts/storage/storage-classes/#mount-options
=> Update mountOptions to separate options

en/deploy-on-aws-eks.md, zh/deploy-on-aws-eks.md
Update example eksctl file to install the ebs-csi-driver addon when creating aws eks cluster
- This PR is relate to: https://github.com/pingcap/docs-tidb-operator/issues/2483
- Other reference link(s): [Amazon EBS CSI driver is now generally available in Amazon EKS add-ons](https://aws.amazon.com/cn/blogs/containers/amazon-ebs-csi-driver-is-now-generally-available-in-amazon-eks-add-ons/)
=> install the ebs-csi-driver addon when creating aws eks cluster

en/deploy-tiproxy.md, zh/configure-a-tidb-cluster.md, zh/deploy-tiproxy.md
Close https://github.com/pingcap/docs-tidb-operator/issues/2498
=> tiproxy: fix broken links

en/configure-a-tidb-cluster.md, en/deploy-tiproxy.md, zh/configure-a-tidb-cluster.md, zh/deploy-tiproxy.md
=> tiproxy: add description on graceful-wait and signing-cert

en/deploy-on-aws-eks.md, zh/deploy-on-aws-eks.md
Close #2509 #2508 #2507 #2506 
The documentation page previous found at `https://eksctl.io/usage/managing-nodegroups/` has been updated to a new URL `https://eksctl.io/usage/nodegroups/`. This change was made in https://github.com/eksctl-io/eksctl/commit/aec56df90f29feeead74d1eb5cd643cda907229f
=> fix a broken link of eksctl

en/clinic-user-guide.md, zh/clinic-user-guide.md
update UI elements on the Clinic Server login page
=> clinic: update UI elements on the login page

en/deploy-cluster-on-arm64.md, en/deploy-on-aws-eks.md, zh/deploy-cluster-on-arm64.md, zh/deploy-on-aws-eks.md
We can use Graviton instances in AWS
=> zh, en: update some instance type for AWS Graviton

en/get-started.md, zh/get-started.md
bump KIND version as we already bump K8s (and its deps)
=> zh, en: bump KIND version

.github/workflows/ci.yaml, .github/workflows/link-fail-fast.yaml, .github/workflows/link.yml, .github/workflows/media.yml, .github/workflows/prevent-deletion.yaml, .github/workflows/vale.yaml
upgrade `actions/checkout` and `actions/setup-node` from v3 to v4 https://github.com/pingcap/docs-tidb-operator/actions/runs/9262796613
=> ci: upgrade actions from v3 to v4

en/configure-a-tidb-cluster.md, zh/configure-a-tidb-cluster.md
TiDB operator v1.6.0 supports assigning node labels to TiProxy labels.
=> en, zh: add TiProxy label description

en/use-tidb-dm.md
[#2586](https://github.com/pingcap/docs-tidb-operator/issues/2586) Example syntax error in eng doc.
Add a hyphen on kubectl command:  from kubectl exec -it - to kubectl exec -it --
because - is not valid syntax, and will throw an error message. Detail inside the #2586 
NA
=> DM: Revise wrong syntax for command example on get into the pod in eng doc

en/configure-tidb-binlog-drainer.md, en/deploy-tidb-binlog.md, zh/configure-tidb-binlog-drainer.md, zh/deploy-tidb-binlog.md
TiDB Binlog will be deprecated starting from TiDB v8.3.0. This PR adds necessary warning and note.
Ref: https://docs.pingcap.com/tidb/v7.5/release-7.5.0#deprecated-features 
=> en, zh: add descriptions for TiDB Binlog deprecation

en/backup-to-aws-s3-using-br.md, en/backup-to-azblob-using-br.md, en/backup-to-gcs-using-br.md, en/backup-to-pv-using-br.md, en/enable-tls-between-components.md, en/enable-tls-for-mysql-client.md, en/restore-from-aws-s3-using-br.md, en/restore-from-azblob-using-br.md, en/restore-from-gcs-using-br.md, en/restore-from-pv-using-br.md, zh/backup-to-aws-s3-using-br.md, zh/backup-to-azblob-using-br.md, zh/backup-to-gcs-using-br.md, zh/backup-to-pv-using-br.md, zh/enable-tls-between-components.md, zh/enable-tls-for-mysql-client.md, zh/restore-from-aws-s3-using-br.md, zh/restore-from-azblob-using-br.md, zh/restore-from-gcs-using-br.md, zh/restore-from-pv-using-br.md
remove `spec.from` for `Backup` using BR and `spec.to` for `Restore` using BR.
not remove these for Dumpling & Lightning
**for v1.4**, I'll open another PR to comment these out (instead of remove them)
=> zh,en: remove spec.from for Backup and spec.to for Restore

en/backup-to-aws-s3-using-br.md, en/backup-to-azblob-using-br.md, en/backup-to-gcs-using-br.md, en/enable-tls-between-components.md, en/enable-tls-for-mysql-client.md, en/restore-from-aws-s3-using-br.md, zh/backup-to-aws-s3-using-br.md, zh/backup-to-azblob-using-br.md, zh/backup-to-gcs-using-br.md, zh/enable-tls-between-components.md, zh/enable-tls-for-mysql-client.md, zh/restore-from-aws-s3-using-br.md
comment out `spec.from` for Backup using BR and `spec.to` for Restore using BR.
not comment out these for Dumpling & Lightning
ref #2614
=> zh, en: comment out spec.from for Backup and spec.to for Restore in v1.4

en/TOC.md, en/releases/release-1.5.4.md, zh/TOC.md, zh/releases/release-1.5.4.md
=> en,zh: add v1.5.4 release notes

en/configure-storage-class.md, zh/configure-storage-class.md
Updates the version of local-volume-provisioner
=> Update the version of local-volume-provisioner

zh/enable-tls-between-components.md
- Other reference link(s):  https://github.com/pingcap/tidb-operator/pull/5708
=> pd/tls: add upgrade tls description

en/_index.md
Removes the word "Documentation" from the banner, for better visual experience
and for consistency with that on https://docs.pingcap.com/tidb/stable , which doesn't use the word "Documentation"
=> en: update the index title for better display

en/deploy-tidb-operator.md, zh/deploy-tidb-operator.md
Updates `pingcap/advanced-statefulset:v0.3.3` to `pingcap/advanced-statefulset:v0.7.0`
=> en, zh: update the version number of advanced-statefulset

en/grant-permissions-to-remote-storage.md, en/renew-tls-certificate.md, zh/grant-permissions-to-remote-storage.md
=>  Add serivce account requirement for tiflash pod while restore

en/TOC.md, en/releases/release-1.5.5.md, zh/TOC.md, zh/releases/release-1.5.5.md
=> en,zh: add v1.5.5 release notes

zh/tidb-operator-overview.md
=> zh: add security notes

en/tidb-toolkit.md, zh/tidb-toolkit.md
=> zh,en: remove deprecated Helm charts

.github/pull_request_template.md
=> fix: update CLA link to correct URL
